cfengine/buildscripts

packaging/cfengine-community/initscript
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> initscript: Fix typo

deps-packaging/apache/httpd.conf
https://dev.cfengine.com/issues/6971
=> Disable directory indexes in mission portal

build-scripts/package
Reflect that the fix in 9dbcdfebd9 really only is for cfengine-nova.
=> Fix cfengine-nova-hub package using scripts from cfengine-nova.

deps-packaging/libcurl/cfbuild-libcurl.spec, deps-packaging/php-svn/cfbuild-php-svn.spec, deps-packaging/php/cfbuild-php.spec
This fixes RHEL7, and I can't quite say how I got it to work before.
=> Fix incorrect flag passed to linker, should have "-Wl," prefix.

deps-packaging/php/cfbuild-php.spec, deps-packaging/php/debian/rules
We have code that depends on it.
=> Redmine #7270: Enable iconv for PHP.

build-scripts/functions, deps-packaging/pkg-cache, packaging/common/script-templates/pkg-script-common.sh
The old approach has been found not to work under some circumstances,
however this approach has been tested and found to work.
=> Fix POSIX shell detection on Solaris.

deps-packaging/php/cfbuild-php.spec, deps-packaging/php/distfiles
=> Upgrade PHP to 5.6.21.

packaging/cfengine-community/cfengine-community.spec.in
Removed versioning completely which is anyway handled by git branches.
=> INF-301: Fix problem with two-digit versions

deps-packaging/git/cfbuild-git.spec, deps-packaging/git/distfiles, deps-packaging/libxml2/cfbuild-libxml2.spec, deps-packaging/libxml2/distfiles, deps-packaging/openssl/cfbuild-openssl.spec, deps-packaging/openssl/distfiles, deps-packaging/openssl/source, deps-packaging/php/cfbuild-php.spec, deps-packaging/php/distfiles, deps-packaging/postgresql-hub/cfbuild-postgresql-hub.spec, deps-packaging/postgresql-hub/distfiles, deps-packaging/postgresql-hub/source
- Git 2.8.3
- lixml2 2.9.4
- OpenSSL 1.0.2h
- PHP 5.6.22
- PostgreSQL 9.5.3
=> Upgrade dependencies to latest versions:

packaging/common/cfengine-hub/postinstall.sh
=> Change: Use more restrictive unix socket perms

packaging/common/cfengine-hub/postinstall.sh
=> Change: Disable TCP and redis

deps-packaging/php/cfbuild-php.spec, deps-packaging/php/debian/rules
=> Change: Reduce php info leak

packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
=> Change: Remove executable bit from systemd units

build-scripts/detect-environment
=> Handle multi-digit version components for CentOS.

build-scripts/package-msi
=> Rewrite package-msi to run on Linux under wine instead of Windows.

build-scripts/package-msi
=> Don't attempt invalid replacement when expression is empty.

packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/preinstall.sh
=> Enable database migration also from 3.9 to 3.10.

build-scripts/build-environment-check
=> Add some more dependencies that need to be present on build slaves.

deps-packaging/libcurl-hub/source, deps-packaging/libcurl/source
=> Update download URL for libcurl.

deps-packaging/pkg-cache
Signed-off-by: Ole Herman Schumacher Elgesem <ole.elgesem@cfengine.com>
=> Print error in buildscript to stderr

deps-packaging/README.md, deps-packaging/git/cfbuild-git.spec, deps-packaging/git/distfiles, deps-packaging/php/cfbuild-php.spec, deps-packaging/php/distfiles, deps-packaging/postgresql-hub/cfbuild-postgresql-hub.spec, deps-packaging/postgresql-hub/distfiles, deps-packaging/postgresql-hub/source, deps-packaging/redis/cfbuild-redis.spec, deps-packaging/redis/distfiles
Minor updates for PHP, Redis, Postgres, Git.
=> Dependency updates

deps-packaging/postgresql-hub/postgresql.conf.cfengine
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
safe for 3.10.x+
=> Enable parallel plans in PG 9.6+

build-scripts/functions, build-scripts/package, build-scripts/prepare-results, packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova/cfengine-nova.spec.in
Not sure what the name of created file should be.
=> ENT-3058: Create a packaged tarball of CFEngine binaries and all dependencies

deps-packaging/README.md, deps-packaging/apache/cfbuild-apache.spec, deps-packaging/apache/distfiles, deps-packaging/autoconf/cfbuild-autoconf.spec, deps-packaging/autoconf/distfiles, deps-packaging/libcurl/cfbuild-libcurl.spec, deps-packaging/libcurl/distfiles, deps-packaging/libcurl/source, deps-packaging/libiconv/cfbuild-libiconv.spec, deps-packaging/libiconv/distfiles, deps-packaging/pcre/cfbuild-pcre.spec, deps-packaging/pcre/distfiles, deps-packaging/php/cfbuild-php.spec, deps-packaging/php/distfiles, deps-packaging/postgresql-hub/cfbuild-postgresql-hub.spec, deps-packaging/postgresql-hub/distfiles, deps-packaging/postgresql-hub/source, deps-packaging/postgresql/cfbuild-postgresql.spec, deps-packaging/postgresql/distfiles, deps-packaging/postgresql/source, deps-packaging/redis/cfbuild-redis.spec, deps-packaging/redis/distfiles
Updated minor versions on master branch.
=> ENT-3074: Update dependencies for 3.10.1 and 3.7.5

deps-packaging/php/cfbuild-php.spec, deps-packaging/php/debian/rules
=> ENT-3131: Set default timezone for php to UTC

packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova/cfengine-nova.spec.aix.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
https://github.com/cfengine/core/pull/2764
=> Added cf-net binary to packaging

packaging/cfengine-nova/cfengine-nova.wxs
Merge with: cfengine/enterprise#338
=> Add cf-net to windows packaging

build-scripts/travis
Note that currently Travis is not enabled for this repo, but will be enabled for several others
=> Add script for building Enterprise package on Travis

deps-packaging/libcurl/source
=> Switch to http mirror for libcurl

build-scripts/travis
Sometimes it might be there, for some reason
=> hide PHP stuff from build process

build-scripts/travis
we have disposable machines, not unlimited disk space!
=> disable chroot testing in travis

build-scripts/compile-options, deps-packaging/php/cfbuild-php.spec, deps-packaging/php/debian/rules
=> ENT-3373: Enable LDAP support in PHP

.travis.yml, build-scripts/travis
Also provide a simple sample .travis.yml file
Note that this PR will break Travis building in other repos, so it should be merged together with relevant PRs to other repos, and after that all PRs in other repos should be rebased.
=> ENT-3277: Update travis to use stages.

packaging/cfengine-nova/cfengine-nova.bff.sh
````
lex@test:~/git/buildscripts$ bash test.sh 3.12.0a.627b6c4
3.12.88.6276
lex@test:~/git/buildscripts$ bash test.sh 3.12.0b1
3.12.991.0
lex@test:~/git/buildscripts$ bash test.sh 3.12.0b2
3.12.992.0
lex@test:~/git/buildscripts$ bash test.sh 3.12.0
3.12.0.0
lex@test:~/git/buildscripts$ bash test.sh 3.12.1
3.12.1.0
````
=> ENT-3268: Convert version number into AIX format

deps-packaging/php/debian/rules
=> ENT-3412: Ensure tabs in debian/rules file

build-scripts/detect-environment
found this while working on pureos (aka debian 10 aka buster)
=> add awareness of debian 10

packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-non-hub/postinstall.sh
=> CFE-2029: Remove package installation of cf-twin

packaging/common/cfengine-hub/postinstall.sh
=> Refresh inventory view after installation.

deps-packaging/README.md, deps-packaging/libcurl/centos4-includes.patch, deps-packaging/libcurl/cfbuild-libcurl.spec, deps-packaging/libcurl/curl_off_t.diff, deps-packaging/libcurl/distfiles
cherry-picks with some changes
=> Upgrade CURL on 3.7.x

deps-packaging/README.md, deps-packaging/libcurl-hub/cfbuild-libcurl-hub.spec, deps-packaging/libcurl-hub/distfiles, deps-packaging/libcurl/centos4-includes.patch, deps-packaging/libcurl/cfbuild-libcurl.spec, deps-packaging/libcurl/curl_off_t.diff, deps-packaging/libcurl/distfiles, deps-packaging/libcurl/hpux/build
=> Upgrade CURL on 3.10.x

build-scripts/travis
=> run apt-get update before apt-get install to make sure all packages exist

packaging/common/cfengine-hub/preinstall.sh
share/GUI dir is managed by package manager, while httpd/htdocs is
populated by MPF with some files later added by PHP scripts.
Before upgrading, we remove all files from httpd/htdocs dir, which have
corresponding files in share/GUI.
If share/GUI dir is not found, but httpd/htdocs exists (it shouldn't
normally happen), we fallback to old method of purging all files except
known exceptions.
=> ENT-3217: nicer httpd/htdocs clean up

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/rules
=> ENT-3668: remove secrets.txt from packaging

build-scripts/travis
Also hide secrets from log and convert tabs to spaces
=> ENT-3525: Run reporting tests in Travis

build-scripts/travis
=> install proper pgtap

build-scripts/travis
https://ci.cfengine.com/job/pr-pipeline/192/
=> Don't fill logs with progress prints

build-scripts/travis
@Lex-2008 please review and merge ;)
=> ENT-3691 fixup TEST_OPTIONS export line so that it works properly.

deps-packaging/pcre/source
=> Update PCRE download link

packaging/common/cfengine-hub/postinstall.sh
Two fallback upgrade mechanisms and manual upgrade instructions
Now, how do I test this?
=> ENT-3648 More complex upgrade strategy

packaging/common/cfengine-hub/postinstall.sh
Two fallback upgrade mechanisms and manual upgrade instructions
=> ENT-3648 More complex database upgrade strategy

packaging/common/cfengine-hub/postinstall.sh
(cherry picked from commit 9946b377b46cc6f7b9330b168dc1e953f294d277)
=> ENT-3906: Set owner of httpd/htdocs as the apache user.

build-scripts/bootstrap-tarballs, build-scripts/set_github_status.sh
We can use this in jenkins to publish the results of jobs.
=> Add a script for setting GitHub commit/PR status

build-scripts/travis
merge with  https://github.com/cfengine/nova/pull/1224
=> ENT-3525: remove pgtap dep for travis

build-scripts/travis, packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova/cfengine-nova.spec.aix.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/cfengine-nova.wxs, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
https://github.com/cfengine/core/pull/3367
https://github.com/cfengine/enterprise/pull/456
https://github.com/cfengine/buildscripts/pull/463
=> ENT-4064: Added cf-check to packaging

packaging/common/cfengine-hub/preinstall.sh, packaging/common/script-templates/script-common.sh
Three things that should fix issues with upgrading from older versions.
=> [3.12.x] upgrade fixes

packaging/common/cfengine-hub/postinstall.sh
merge with https://github.com/cfengine/core/pull/3299 and  https://github.com/cfengine/nova/pull/1247
=> ENT-4079 DC-to-VSC migration

deps-packaging/postgresql-hub/postgresql.conf.cfengine.patch
=> Fix the patch file for postgresql.conf to apply

build-scripts/travis, packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova/cfengine-nova.spec.aix.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/cfengine-nova.wxs, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
https://github.com/cfengine/core/pull/3425
https://github.com/cfengine/masterfiles/pull/1274
https://github.com/cfengine/buildscripts/pull/492
https://github.com/cfengine/enterprise/pull/470
=> WIP ENT-4064: Backport cf-check diagnose to 3.12.1

packaging/common/script-templates/script-common.sh
=> Start Redis after upgrade if it was running before it

packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/preinstall.sh, packaging/common/cfengine-hub/preremove.sh, packaging/common/cfengine-non-hub/postremove.sh, packaging/common/cfengine-non-hub/preinstall.sh, packaging/common/produce-script, packaging/common/script-templates/script-common.sh
All the failures in the scriptlets should generally be fatal. We
may need to identify some exceptions where we will do 'set +x'
locally.
Ticket: ENT-3385
=> Set -e in package scriptlets

packaging/common/script-templates/script-common-header-last.sh
(cherry picked from commit 3204fb47eda9dbae2217f563cfe5a1c03538211b)
=> ENT-4506 Set explicit permissions on the install log file (3.12.x)

packaging/common/script-templates/script-common-header-last.sh
(cherry picked from commit 3204fb47eda9dbae2217f563cfe5a1c03538211b)
=> ENT-4506 Set explicit permissions on the install log file (3.10.x)

deps-packaging/postgresql-hub/CVE-2019-10164.1.patch, deps-packaging/postgresql-hub/CVE-2019-10164.2.patch, deps-packaging/postgresql-hub/cfbuild-postgresql-hub.spec, deps-packaging/postgresql-hub/debian/rules
very much like https://github.com/cfengine/buildscripts/pull/583, but for different PostgreSQL version
=> 3.14.0-x PR

build-scripts/travis
merge with https://github.com/cfengine/nova/pull/1465
=> ENT-4670: Added schema tests to nova build.

build-scripts/travis
New version of `s3cmd` asks one more question to which we accept a default answer
=> ENT-4889 Adapt travis script to updated s3cmd

build-scripts/labels.txt, build-scripts/package, packaging/cfengine-nova/coreos/install.sh, packaging/cfengine-nova/coreos/systemd/cf-execd.service, packaging/cfengine-nova/coreos/systemd/cf-monitord.service, packaging/cfengine-nova/coreos/systemd/cf-serverd.service, packaging/cfengine-nova/coreos/systemd/cfengine3.service, packaging/cfengine-nova/coreos/systemd/var-cfengine.mount, packaging/cfengine-nova/coreos/uninstall.sh
Reverts cfengine/buildscripts#595
=> Bring back ENT-4758 ￼Create tarball with a filesystem image and accompanying files

build-remote
=> Fixed build-remote to run outside of buildscripts

build-scripts/package-msi, packaging/cfengine-nova/cfengine-nova.wxs
Merge together with:
https://github.com/cfengine/buildscripts/pull/590
=> ENT-4901 create ssl dir on Windows

build-scripts/build-environment-check, build-scripts/compile, build-scripts/configure, build-scripts/detect-environment, build-scripts/functions, build-scripts/labels.txt, deps-packaging/git/cfbuild-git.spec, packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/rules, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova-hub/debian/rules, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
Small bits and pieces to make builds on RHEL 8 possible and resulting **agent** (for now) packages working.
https://github.com/cfengine/core/pull/3813
https://github.com/cfengine/masterfiles/pull/1492
https://github.com/cfengine/buildscripts/pull/612
=> RHEL 8 support

deps-packaging/lmdb/0001-Do-not-abort-if-a-user-define-assert-function-is-cal.patch
We want to have a chance to handle the failure gracefully.
https://github.com/cfengine/core/pull/3820
https://github.com/cfengine/buildscripts/pull/614
=> Patch LMDB to not abort on assert failure

deps-packaging/README.md, deps-packaging/libcurl-hub/cfbuild-libcurl-hub.spec, deps-packaging/libcurl-hub/distfiles, deps-packaging/libcurl/cfbuild-libcurl.spec, deps-packaging/libcurl/distfiles, deps-packaging/libcurl/hpux/build, deps-packaging/libcurl/solaris/build, deps-packaging/openssl/0001-Revert-Fix-default-installation-paths-on-mingw.patch, deps-packaging/openssl/cfbuild-openssl.spec, deps-packaging/openssl/distfiles, deps-packaging/openssl/mingw/debian/rules, deps-packaging/php/cfbuild-php.spec, deps-packaging/php/distfiles, deps-packaging/postgresql/cfbuild-postgresql.spec, deps-packaging/postgresql/distfiles, deps-packaging/postgresql/source
Update openssl from 1.1.1c to 1.1.1d
Update libcurl-hub from 7.65.3 to 7.66.0
Update postgresql from 12beta3 to 12.0
Update php from 7.3.8 to 7.3.10
Update libcurl from 7.65.3 to 7.66.0
=> Dependency updates for master

deps-packaging/apache/httpd.conf
Ticket: ENT-5138
https://github.com/cfengine/masterfiles/pull/1602
https://github.com/cfengine/mission-portal/pull/963
https://github.com/cfengine/nova/pull/1561
=> Added username from apache request notes to access log

deps-packaging/apache/httpd.conf
Ticket: ENT-5138
(cherry picked from commit 6c617d4b28681a58c5cde70a74f8d988a0df0744)
https://github.com/cfengine/mission-portal/pull/970
https://github.com/cfengine/nova/pull/1569
https://github.com/cfengine/masterfiles/pull/1617
=> Added username from apache request notes to access log (3.12.x)

packaging/common/cfengine-hub/postinstall.sh
(cherry picked from commit 65ff48e30679d9edc1f050f91a007750737181d2)
=> Move userworkdir manipulation commands after its mkdir command

build-scripts/build-environment-check, build-scripts/compile, build-scripts/configure, build-scripts/detect-environment, build-scripts/functions, build-scripts/labels.txt, deps-packaging/git/cfbuild-git.spec, packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/rules, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova-hub/debian/rules, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
https://github.com/cfengine/buildscripts/pull/632
https://github.com/cfengine/core/pull/3913
https://github.com/cfengine/enterprise/pull/558
https://github.com/cfengine/nova/pull/1539
https://github.com/cfengine/masterfiles/pull/1639
=> [3.12.x] RHEL 8

packaging/common/cfengine-hub/postinstall.sh
Ticket: ENT-5115
https://github.com/cfengine/nova/pull/1573
https://github.com/cfengine/buildscripts/pull/659
https://github.com/cfengine/mission-portal/pull/988
=> ENT-5115 Added checks for database state to avoid error messages during install

packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova/cfengine-nova.spec.aix.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/cfengine-nova.wxs, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
Signed-off-by: Ole Herman Schumacher Elgesem <ole.elgesem@cfengine.com>
https://github.com/cfengine/core/pull/4051
https://github.com/cfengine/buildscripts/pull/678
=> Added cf-keycrypt to buildscripts

build-scripts/travis
https://github.com/cfengine/buildscripts/pull/711
https://github.com/cfengine/nova/pull/1653
=> Backported nova/tests/schema travis CI tests to 3.12.x

build-scripts/configure, build-scripts/package, build-scripts/version
And make sure it is available when './configure' is run in our
repositories.
Ticket: CFE-3290
=> Resolve the RELEASE number together with version

build-scripts/configure, build-scripts/package, build-scripts/version
And make sure it is available when './configure' is run in our
repositories.
Ticket: CFE-3290
(cherry picked from commit d1b18b07328c0f24a17c7bb066e343db207f1273)
=> [3.15.x] Resolve the RELEASE number together with version

deps-packaging/libyaml/debian/cfbuild-libyaml-devel.install, deps-packaging/libyaml/debian/cfbuild-libyaml.install
=> ENT-5431: Added /var/cfengine/lib to install files for libyaml

build-scripts/travis
=> Install Mission Portal Javascript dependencies fron NPM

build-scripts/travis
=> Check if npm config file exists to avoid errors

deps-packaging/README.md, deps-packaging/openssl/cfbuild-openssl.spec, deps-packaging/openssl/distfiles
Hopefully this fixes some of the 404 errors we've seen.
=> Updated openssl 1.1.1d -> 1.1.1f

deps-packaging/README.md, deps-packaging/openssl/cfbuild-openssl.spec, deps-packaging/openssl/distfiles
Hopefully this fixes some of the 404 errors we've seen.
=> Updated openssl 1.1.1d -> 1.1.1f (3.15)

packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/preinstall.sh
https://github.com/cfengine/nova/pull/1613
https://github.com/cfengine/mission-portal/pull/1036
https://github.com/cfengine/ldap-api/pull/14
https://github.com/cfengine/buildscripts/pull/696
=> ENT-5369 Create secrets.ini

build-scripts/bootstrap-tarballs, build-scripts/travis, deps-packaging/apache/httpd.conf, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/rules, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/preinstall.sh
Ticket: ENT-5372
Merge together: 
https://github.com/cfengine/masterfiles/pull/1698
https://github.com/cfengine/buildscripts/pull/694
https://github.com/cfengine/nova/pull/1633
https://github.com/cfengine/mission-portal/pull/1051
=> Front controller and static files of Mission portal were moved to public directory

packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova/cfengine-nova.spec.aix.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/cfengine-nova.wxs, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
=> Rename cf-keycrypt -> cf-secret

build-scripts/bootstrap-tarballs, build-scripts/travis
=> Installed Mission Portal PHP dependencies in Travis and Jenkins jobs

packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/rules, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/rules, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-non-hub/postinstall.sh
From now on, it will be managed by masterfiles.
----
#
=> CFE-3237 Do not touch package modules

deps-packaging/openssl/cfbuild-openssl.spec, deps-packaging/openssl/openssl-1.1.1-evp-kdf.patch
This API is needed by PAM on RHEL 8.
Ticket: ENT-5564
=> Add EVP_KDF API to OpenSSL we build for RHEL

packaging/common/cfengine-hub/postinstall.sh
=> Fixed PHP and JS dependencies permissions

build-scripts/package
(cherry picked from commit ae31520966e20179ad89df67d6f7c32d51459a5f)
----
#
=> specify OS name in deb packages

packaging/cfengine-nova/cfengine-nova.bff.sh
=> ENT-5967 Correct release AIX version

packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova/cfengine-nova.spec.aix.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/cfengine-nova.wxs, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
https://github.com/cfengine/core/pull/4204
https://github.com/cfengine/enterprise/pull/620
https://github.com/cfengine/buildscripts/pull/750
=> [3.15.x] cf-secret

packaging/cfengine-nova/cfengine-nova.bff.sh
=> ENT-5967 Correct release AIX version - 3.15.x

packaging/cfengine-nova/cfengine-nova.bff.sh
=> ENT-5967 Correct release AIX version - 3.12.x

build-scripts/package
=> ENT-4981 Add build number to coreos and generic tarballs

build-scripts/labels.txt
=> ENT-5335 Add SLES 11 to Jenkins

build-scripts/labels.txt
=> ENT-5335 Add SLES 12 to Jenkins

build-scripts/labels.txt
(cherry picked from commit 73bcb10eb25e0e8ae0f7fc63d68745190faa3459)
----
#
=> ENT-5335 Add SLES 12 to Jenkins - 3.15.x

build-scripts/labels.txt
(cherry picked from commit 73bcb10eb25e0e8ae0f7fc63d68745190faa3459)
----
#
=> ENT-5335 Add SLES 12 to Jenkins - 3.12.x

build-scripts/travis
Ticket: ENT-6160
https://github.com/cfengine/mission-portal/pull/1202
https://github.com/cfengine/nova/pull/1700
https://github.com/cfengine/buildscripts/pull/764
=> ENT-6160: Altered schema-test to work with nova or mission-portal

build-scripts/labels.txt, deps-packaging/libcurl-hub/cfbuild-libcurl-hub.spec, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh
https://github.com/cfengine/buildscripts/pull/775
https://github.com/cfengine/core/pull/4326
=> [3.15.x] RHEL 8 hub

deps-packaging/apache/httpd.conf
=> Added redirect to remove index.php from Mission Portal's URL

.mailmap
Discovered while running shortlog commands for:
https://cfengine.com/company/blog-detail/2020-retrospective/
=> Added Aleksei and Ihor aliases to mailmap

deps-packaging/apache/httpd.conf
=> Do not apply redirect from index.php to internal APIs

deps-packaging/php/cfbuild-php.spec, deps-packaging/php/debian/rules
=> Enabled sockets in PHP

deps-packaging/apache/httpd.conf
=> Fixed broken redirect from http to htttps

build-scripts/bootstrap-tarballs, build-scripts/travis
=> Installed LDAP API dependencies in bootstrap jobs

build-scripts/bootstrap-tarballs, build-scripts/travis
=> Compiled Mission portal styles in bootstrap jobs

build-scripts/bootstrap-tarballs, build-scripts/travis
=> Installed LDAP API dependencies in bootstrap jobs (3.18.x)

build-scripts/bootstrap-tarballs, build-scripts/travis
Ticket: ENT-6007
(cherry picked from commit 45d59474c0f5deb1f4197222aff5f6d9a6ae2149)
=> Compiled Mission portal styles in bootstrap jobs (3.18.x)

deps-packaging/apache/httpd.conf
=> Deny static directory in httpd.conf (3.15.x)

deps-packaging/apache/httpd.conf
Ticket: ENT-7465
(cherry picked from commit 372ee0b9d894d0789d662fcc0d934277ab09d3ed)
=> Deny static directory in httpd.conf (3.12.x)

deps-packaging/diffutils/cfbuild-diffutils-aix.spec, deps-packaging/diffutils/distfiles, deps-packaging/pkg-build-rpm
=> ENT-7741 Upgrade diffutils 3.7 to 3.8 and add '-pthread' linker option on AIX 

deps-packaging/apache/httpd.conf
=> Moved httpd.pid to root of httpd workdir

deps-packaging/apache/httpd.conf
(cherry picked from commit 30588ab261de8da40dbbe8e02a927ed1575a6f99)
=> ENT-7966: Moved httpd.pid to root of httpd workdir (3.18)

deps-packaging/apache/httpd.conf
(cherry picked from commit 30588ab261de8da40dbbe8e02a927ed1575a6f99)
=> ENT-7966: Moved httpd.pid to root of httpd workdir (3.15)

deps-packaging/apache/cfbuild-apache.spec, deps-packaging/apache/debian/rules
Ticket: ENT-7948
(cherry picked from commit ddf7045322fa60db1894acc9e9d1cd3049165bd2)
=> Ensure files created by Apache are not readable by others - 3.15.x

deps-packaging/apache/cfbuild-apache.spec, deps-packaging/apache/debian/rules
Ticket: ENT-7948
(cherry picked from commit ddf7045322fa60db1894acc9e9d1cd3049165bd2)
=> Ensure files created by Apache are not readable by others - 3.18.x

deps-packaging/apache/cfbuild-apache.spec, deps-packaging/apache/debian/rules
=> Ensure files created by Apache are not readable by others

deps-packaging/apache/httpd.conf
(cherry picked from commit 1dce0be515d381af3840dc8e348c01abb3b5a182)
=> ENT-7966: Fixed path to httpd.pid (3.15)

deps-packaging/apache/httpd.conf
(cherry picked from commit 1dce0be515d381af3840dc8e348c01abb3b5a182)
=> ENT-7966: Fixed path to httpd.pid (3.18)

deps-packaging/apache/httpd.conf
=> ENT-7966: Fixed path to httpd.pid

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/common/cfengine-hub/postinstall.sh
Ticket: ENT-7961
(cherry picked from commit 94f0cc21c82424049a426aa4b09e716f223b621b)
=> ENT-7961: Enforced permissions for Postgres log (3.18)

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/common/cfengine-hub/postinstall.sh
Ticket: ENT-7961
(cherry picked from commit 94f0cc21c82424049a426aa4b09e716f223b621b)
=> ENT-7961: Enforced permissions for Postgres log (3.15)

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
=> Do not create postgresql.log as a directory

build-scripts/labels.txt
Ticket: ENT-7972
(cherry picked from commit c436ff4dae6e3f056101458ac3fed00d16be3b3b)
=> added debian11 to the 3.18.x mix

build-scripts/prepare-testmachine-chroot, build-scripts/transfer-to-testmachine
In order to keep Jenkins _entertained_ during long transfers
Ticket: INF-2303
=> add keepalive echo

packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/preremove.sh, packaging/common/cfengine-non-hub/postremove.sh, packaging/common/cfengine-non-hub/preremove.sh
=> ENT-7357: Add cf-reactor as a new service

packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/preremove.sh, packaging/common/cfengine-non-hub/postremove.sh, packaging/common/cfengine-non-hub/preremove.sh
Ticket: ENT-7357
(cherry picked from commit cab82a0217c28d347187d8ba5a6a47e38dbf407c)
=> [3.18.x] Add cf-reactor as a new service

packaging/common/script-templates/script-common-header-last.sh
=> Name install logs uniquely

packaging/common/script-templates/script-common-header-last.sh
Ticket: ENT-8342
(cherry picked from commit b3f72b324ca7cb1de5cc1f3f3f3a4a0bfac15188)
=> Name install logs uniquely - 3.18.x

packaging/common/script-templates/script-common-header-last.sh
Ticket: ENT-8342
(cherry picked from commit b3f72b324ca7cb1de5cc1f3f3f3a4a0bfac15188)
=> Name install logs uniquely - 3.15.x

packaging/common/cfengine-hub/postinstall.sh
=> Protect postinst script against selinux-related failures

packaging/common/cfengine-hub/postinstall.sh
Ticket: CFE-3720
(cherry picked from commit e53866de0a1884814de8c2bd381e4091b72e0d72)
=> Protect postinst script against selinux-related failures - 3.18.x

packaging/common/cfengine-hub/postinstall.sh
Ticket: CFE-3720
(cherry picked from commit e53866de0a1884814de8c2bd381e4091b72e0d72)
=> Protect postinst script against selinux-related failures - 3.15.x

packaging/common/cfengine-hub/preinstall.sh
=> Better way of killing httpd on upgrade - 3.15.x

packaging/common/cfengine-hub/preinstall.sh
=> Better way of killing httpd on upgrade - 3.18.x

build-scripts/bootstrap-tarballs, build-scripts/travis
Ticket: ENT-5567
Merge together: https://github.com/cfengine/mission-portal/pull/1680
=> Removed jquery-ui building from source

deps-packaging/apache/apachectl.patch, deps-packaging/apache/cfbuild-apache.spec, deps-packaging/apache/debian/rules
(cherry picked from commit 191cfc9621f5d003bc83cfc3e2d76104d5b27ab2)
=> patch apachectl to be more resillient - 3.15.x

deps-packaging/apache/apachectl.patch, deps-packaging/apache/cfbuild-apache.spec, deps-packaging/apache/debian/rules
(cherry picked from commit 191cfc9621f5d003bc83cfc3e2d76104d5b27ab2)
=> patch apachectl to be more resillient - 3.18.x

deps-packaging/apache/apachectl.patch, deps-packaging/apache/cfbuild-apache.spec, deps-packaging/apache/debian/rules
=> patch apachectl to be more resillient

build-scripts/bootstrap-tarballs, build-scripts/travis
Ticket: ENT-8825
merge together: https://github.com/cfengine/nova/pull/1905
=> Install nova's PHP dependencies from composer

build-scripts/bootstrap-tarballs, build-scripts/travis
Ticket: ENT-8825
(cherry picked from commit 6cc7004607ddcacde0765cfaf239c93342555095)
merge together: https://github.com/cfengine/nova/pull/1906
=> Install nova's PHP dependencies from composer (3.18.x)

packaging/cfengine-nova/cfengine-nova.bff.sh
=> Remove extra 'cfengine' prefix from bff filename

build-scripts/configure
otherwise, we pick wrong pkg-config file
Ticket: ENT-9059
=> explicitly set PKG_CONFIG_PATH

build-scripts/test-on-thismachine
…nd ubuntu 22 build host"
This reverts commit b16e4ee99bf7e5e10258d8a3b0a8c986855fdefe.
(cherry picked from commit 454dbdb3d0198a0a49c11a2d03d13881c4a6df86)
=> CFE-4010: Revert "Workaround automake version problems between bootstrap host a… (3.18)

package-nova-hub.sh, packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova-hub/debian/rules, packaging/cfengine-nova/cfengine-nova.spec.aix.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
Ticket: ENT-9037
https://github.com/cfengine/core/pull/5010
https://github.com/cfengine/nova/pull/1918
https://github.com/cfengine/buildscripts/pull/1106
https://github.com/cfengine/system-testing/pull/445
=> ENT-9037: Added cf-support binary to packages 

package-nova-hub.sh, packaging/cfengine-community/cfengine-community.spec.in, packaging/cfengine-community/debian/cfengine-community.install, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install, packaging/cfengine-nova-hub/debian/rules, packaging/cfengine-nova/cfengine-nova.spec.aix.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/cfengine-nova/debian/cfengine-nova.install, packaging/cfengine-nova/freebsd/pkg-plist.foot, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-hub/postremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/postremove.sh
=> ENT-9037: Added cf-support binary to packages (3.18)

build-scripts/labels.txt
Ticket: ENT-8479
https://github.com/cfengine/buildscripts/pull/1121
https://github.com/mendersoftware/infra/pull/295
=> ENT-8479: Added ubuntu_22 hub and agent packages configuration

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/control
=> Added libexpat as explicit dependency

build-scripts/bootstrap-tarballs
Ticket: ENT-8476
ChangLog: Title
=> Add Red Hat Text font to TCPDF library

build-scripts/bootstrap-tarballs
Ticket: ENT-8476
ChangLog: Title
(cherry picked from commit 2e8b667f9831ea8c1966af532831ac5a69db3261)
=> Add Red Hat Text font to TCPDF library (3.18.x)

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/rules
=> Set cfbs 2.4.3 version that will be shipped together with hub packages

packaging/common/cfengine-hub/preinstall.sh
=> Ensure postgresql is not running before moving its files, not after

packaging/common/cfengine-hub/preinstall.sh
Ticket: ENT-9547
(cherry picked from commit d18083d11c59399d004f4c4299085604db4d84e9)
=> Ensure postgresql is not running before moving its files, not after - 3.18.x

packaging/common/cfengine-hub/preinstall.sh
Ticket: ENT-9547
(cherry picked from commit d18083d11c59399d004f4c4299085604db4d84e9)
=> Ensure postgresql is not running before moving its files, not after - 3.15.x

deps-packaging/libxml2/cfbuild-libxml2.spec, deps-packaging/libxml2/distfiles, deps-packaging/libxml2/source
Updated libxml2 from 2.9.14 to 2.10.3
=> Updated libxml2 from 2.9.14 to 2.10.3

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/rules
=> ENT-9525: Put cfbs 3.2.2 into hub packages

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/rules
See:
https://github.com/cfengine/cfbs/releases/tag/3.2.4
=> Upgraded cfbs to 3.2.4

build-scripts/configure, build-scripts/labels.txt, deps-packaging/cache-sftp, packaging/common/cfengine-hub/preremove.sh, packaging/common/cfengine-non-hub/postinstall.sh, packaging/common/cfengine-non-hub/preremove.sh
Ticket: ENT-9621
https://github.com/cfengine/buildscripts/pull/1159
https://github.com/cfengine/core/pull/5114
https://github.com/cfengine/masterfiles/pull/2544
=> ENT-9621: Added support for redhat 9 agent (3.18)

packaging/common/cfengine-hub/postinstall.sh
Ticket: ENT-9174
Merge together: https://github.com/cfengine/masterfiles/pull/2546
=> Align postinst script perms with policy

deps-packaging/apache/httpd.conf
=> Update httpd.conf file with rendered version from masterfiles 

deps-packaging/apache/httpd.conf
Ticket: ENT-9603
(cherry picked from commit e1656dc6e23dac8ebf2485ad523890a55a2c35d4)
=> Update httpd.conf file with rendered version from masterfiles - 3.18.x

packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/rules
Includes fixes needed for 3.21.0 release
=> Upgrade cfbs to 3.2.7

build-scripts/package, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-non-hub/postinstall.sh
https://github.com/cfengine/core/pull/5146
https://github.com/cfengine/buildscripts/pull/1187
=> ENT-9685: Added selinux policy source files and instructions on how to use them

build-scripts/package, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-non-hub/postinstall.sh
with https://github.com/cfengine/core/pull/5161
=> ENT-9685: Added selinux policy source files and instructions on how to use them (3.18)

build-scripts/package, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova/cfengine-nova.spec.in, packaging/common/cfengine-hub/postinstall.sh, packaging/common/cfengine-non-hub/postinstall.sh
with https://github.com/cfengine/core/pull/5160
=> ENT-9685: Added selinux policy source files and instructions on how to use them (3.21)

README.md
now that all dependency updates are merged, we can update an overview table of them
=> Update dependency tables

build-scripts/exotics.txt
=> INF-3402: Removed aix71 exotic while build host is being built

ci/build.sh, ci/clean-build-package.sh, ci/docker-build-package.sh, deps-packaging/zlib/source
- Modified zlib URL to adjust for new release
- Refactored sftp cache ssh key usage into the docker container for full pull/push usage
=> ENT-9517: Modified zlib URL to adjust for new release (3.18)

ci/build.sh, ci/clean-build-package.sh, ci/docker-build-package.sh, deps-packaging/zlib/source
- Modified zlib URL to adjust for new release
- Refactored sftp cache ssh key usage into the docker container for full pull/push usage
=> ENT-9517: Modified zlib URL to adjust for new release (3.21)

ci/package-sha.sh, packaging/common/cfengine-hub/postinstall.sh
- Fixed issue with using pg_upgrade on ubuntu-16 hub installer upgrade
- Fixed ci/package-sha.sh
=> ENT-10710: Fixed issue with using pg_upgrade on ubuntu-16 hub installer upgrade (3.18)

ci/package-sha.sh, packaging/common/cfengine-hub/postinstall.sh
- Fixed issue with using pg_upgrade on ubuntu-16 hub installer upgrade
- Fixed ci/package-sha.sh
=> ENT-10710: Fixed issue with using pg_upgrade on ubuntu-16 hub installer upgrade (3.21)

ci/clean-build-package.sh
Check if things exist before trying to remove them.
Ticket: none
=> Improved ci/clean-build-package.sh for use on a new system

ci/clean-build-package.sh
Check if things exist before trying to remove them.
Ticket: none
(cherry picked from commit d8bac4df2d8ce5a26f79ebb8b1c5d5edeeacf9bd)
=> Improved ci/clean-build-package.sh for use on a new system (3.18)

ci/clean-build-package.sh
Check if things exist before trying to remove them.
Ticket: none
(cherry picked from commit d8bac4df2d8ce5a26f79ebb8b1c5d5edeeacf9bd)
=> Improved ci/clean-build-package.sh for use on a new system (3.21)

ci/Dockerfile-cfengine-build-package, ci/docker-build-package.sh, ci/setup.sh
Needed -y (yes)
Ticket: ENT-10896
(cherry picked from commit 8f0d7d76698ffab24ba5b2778142093134ca14c3)
=> ENT-10896: Fixed build container setup apt install apt-utils problem (3.18)

ci/Dockerfile-cfengine-build-package, ci/docker-build-package.sh, ci/setup.sh
Needed -y (yes)
Ticket: ENT-10896
(cherry picked from commit 8f0d7d76698ffab24ba5b2778142093134ca14c3)
=> ENT-10896: Fixed build container setup apt install apt-utils problem (3.21)

.github/workflows/deployment-tests.yml, ci/deployment-tests.sh
=> ENT-10989: Gather install logs in deployment-test if package fails to install

.github/workflows/deployment-tests.yml, ci/deployment-tests.sh
Ticket: ENT-10989
(cherry picked from commit 8d21263e83bbf038080831d3265798dfdb0c9e70)
=> ENT-10989: Gather install logs in deployment-test if package fails to install (3.18)

.github/workflows/deployment-tests.yml, ci/deployment-tests.sh
Ticket: ENT-10989
(cherry picked from commit 8d21263e83bbf038080831d3265798dfdb0c9e70)
=> ENT-10989: Gather install logs in deployment-test if package fails to install (3.21)

ci/cfengine-build-host-setup.cf, ci/linux-install-jdk21.sh, ci/setup-cfengine-build-host.sh
=> ENT-11166: Added scripts and policy to setup CFEngine build hosts

ci/cfengine-build-host-setup.cf, ci/install-python2-pip.sh
=> ENT-11166: Ubuntu-20 build host needs psycopg2 for python2

ci/linux-install-jdk21.sh
=> ENT-11166: Adjust linux-install-jdk21.sh to set jdk21 java as very high priority

ci/cfengine-build-host-setup.cf, ci/linux-install-jdk21.sh, ci/setup-cfengine-build-host.sh
Apparently it can't handle tabs.
=> ENT-11166: Fixes to build host setup for centos-6 hosts

ci/cfengine-build-host-setup.cf
Instead of adding --nobest option to commands, rework the /etc/(yum&dnf).conf files
=> ENT-11166: Adjusted rhel-8 and rhel-9 build host setup to use best=False

ci/cfengine-build-host-setup.cf, ci/setup-cfengine-build-host.sh
=> ENT-11166: Fixup rhel-8 and rhel-9 build host setup

ci/setup-cfengine-build-host.sh
=> ENT-11166: Fixup Ubuntu-16 build host setup

build-scripts/install-dependencies, deps-packaging/lmdb/cfbuild-lmdb.spec, deps-packaging/lmdb/debian/rules, deps-packaging/pkg-build-rpm
So that we can get nice frames in backtraces including liblmdb.so.
Ticket: ENT-9198
=> Configure LMDB with debug symbols

ci/cfengine-build-host-setup.cf
=> ENT-11166: Be more precise about suse groups search in build host policy

ci/cfengine-build-host-setup.cf, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
=> ENT-11338: Adjusted cfbs packaging on rhel-8 to use platform-python

ci/junit-text-summary.sh
=> ENT-11400: Added junit-text-summary.sh for general use in github workflows

ci/junit-text-summary.sh
Ticket: ENT-11400
(cherry picked from commit 6a17054df8fe35b70a9cc4d20585f66941ae45bd)
=> ENT-11400: Added junit-text-summary.sh for general use in github workflows (3.18)

ci/junit-text-summary.sh
Ticket: ENT-11400
(cherry picked from commit 6a17054df8fe35b70a9cc4d20585f66941ae45bd)
=> ENT-11400: Added junit-text-summary.sh for general use in github workflows (3.21)

ci/setup-cfengine-build-host.sh
=> Update quick install script checksum after an official change was made

ci/cfengine-masterfiles-3.21.4-1.pkg.tar.gz.sha256, ci/quick-install-cfengine-enterprise.sh.sha256, ci/setup-cfengine-build-host.sh
=> Split out checksums for build host setup script to enable automating CI checks when they change

ci/setup-cfengine-build-host.sh
=> Fixed path to build host setup checksum files

packaging/common/cfengine-hub/preinstall.sh
This change simply aims to make the amount of free disk space desired more clear.
Ticket: ENT-11835
=> ENT-11835: Improved messages about free space desired for hub upgrade

build-scripts/bootstrap-tarballs, ci/setup-projects.sh, packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in, packaging/cfengine-nova-hub/debian/rules
=> ENT-11212: Do not ship ldap and api unit tests in release packages

ci/junit-text-summary.sh
=> Fixed junit-text-summary.sh in case selenium tests don't run at all

ci/junit-text-summary.sh
Ticket: none
(cherry picked from commit a4bdb3b83545219c2ffe08ae72310786e8c4d6c1)
=> Fixed junit-text-summary.sh in case selenium tests don't run at all (3.21)

ci/junit-text-summary.sh
Ticket: none
(cherry picked from commit a4bdb3b83545219c2ffe08ae72310786e8c4d6c1)
=> Fixed junit-text-summary.sh in case selenium tests don't run at all (3.18)

ci/Dockerfile-cfengine-build-package, ci/junit-text-summary.sh
=> When the junit xml file is not found, exit 0 to show a nicer result in GH actions summary

ci/cfengine-masterfiles-3.21.4-1.pkg.tar.gz.sha256, ci/cfengine-masterfiles-3.21.5-1.pkg.tar.gz.sha256, ci/quick-install-cfengine-enterprise.sh.sha256, ci/setup-cfengine-build-host.sh
=> ENT-11898: Adjusted quickinstall and masterfiles downloads to latest LTS: 3.21.5. Updated checksums.

ci/quick-install-cfengine-enterprise.sh.sha256, ci/setup-cfengine-build-host.sh
Also added some debug logging to help when checksums don't match
=> Updated quick install script checksum in setup-cfengine-build-host.sh

ci/setup-cfengine-build-host.sh
Apparently git log -1 never completes due to
WARNING: terminal is not fully functional
So try git rev-parse HEAD instead
=> ENT-11898: Adjusted setup build host script for AWS environment

ci/setup-cfengine-build-host.sh
Fixed up a git error on suse-12 and suse-15 platforms.
Ticket: ENT-11928
=> QA: Update setup-cfengine-build-host.sh

packaging/cfengine-community/cfengine-community.spec.in
=> Fix RHEL version check in cfengine-community.spec.in

packaging/cfengine-community/cfengine-community.spec.in
=> Fix profile.d script name in cfengine-community.spec.in

build-scripts/labels.txt
=> Update platforms supported based on platform survey

ci/quick-install-cfengine-enterprise.sh.sha256
=> Update quick-install script sha for build host setup script

README.md
- Update dependency tables
- Remove out-dated mention of autoconf 2.69
=> deptables 2024 10 09 14 54 06 367122

build-scripts/bootstrap-tarballs, ci/setup-projects.sh
Ticket: ENT-11495
together:
https://github.com/cfengine/mission-portal/pull/2620
https://github.com/cfengine/buildscripts/pull/1492
=> ENT-12149: added step to build react components

build-scripts/bootstrap-tarballs, ci/setup-projects.sh
Ticket: ENT-11495
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>
(cherry picked from commit 7902924ad42de3cd39d5139d74335c51da7b10ce)
=> ENT-12149: added step to build react components (3.24.x)

packaging/common/cfengine-hub/postinstall.sh
Ticket: ENT-12383
(cherry picked from commit 8f0d7d76698ffab24ba5b2778142093134ca14c3)
=> Fixed problem with package upgrade not trying other migration methods if pg_upgrade fails (3.24)

build-scripts/build-environment-check
(cherry picked from commit 722f5b7d4deb8a93364d24290cf903bd316c1669)
=> Update build-environment-check for centos-6 rpm-build (3.24)

build-scripts/build-environment-check
(cherry picked from commit 722f5b7d4deb8a93364d24290cf903bd316c1669)
=> Update build-environment-check for centos-6 rpm-build (3.21)

ci/cfengine-build-host-setup.cf
And alphabetized the packages in that group.
It was a small portion so didn't want two commits: one for alpha, one for fix.
Ticket: ENT-12451
=> Restored rpm-build package installation for suse build hosts

ci/quick-install-cfengine-enterprise.sh.sha256
=> Upaded quick install script checksum after update for aarch64 hub installs

build-scripts/labels.txt
=> Remove unsupported platforms from 3.24.x series

build-scripts/configure
=> Added librsync to buildscript configure

ci/setup-cfengine-build-host.sh
Ticket: ENT-12498
Changelog: none.
=> Adjusted build host script to allow for not using git

README.md
- **README.md: Switched to HTTPS urls in dependency tables**
- **README.md: Replaced broken links**
=> README.md: Switched to HTTPS urls in dependency tables

build-scripts/bootstrap-tarballs, ci/setup-projects.sh
=> chore: exclude npm dev dependencies from a package

.github/workflows/build-using-buildscripts.yml, .github/workflows/deployment-tests.yml, .github/workflows/update-deps.yml
- **GH Actions: Reformatted with prettier**
- **update-deps.yml: Replaced non-ascii dashes / hyphens with ascii equivalent**
=> GH Actions: Reformatted and asciified

packaging/common/cfengine-hub/preinstall.sh
- Check if a server is listening on port 9000.
- If the process belongs to a previous CFEngine deployment, attempt to terminate it using fuser.
- Abort installation if termination fails or if the process does not belong to CFEngine.
Ticket: ENT-12704
=> ENT-12704: Ensured PHP-FPM is terminated before installation

.github/workflows/update-dep-tables.yml, .github/workflows/update-deps.yml
Hoping that pull-requests is enough and removing contents
limits access to other things (like releases).
=> GH Actions: Removed contents write permission

deps-packaging/php/debian/rules
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12067)](https://ci.cfengine.com/job/pr-pipeline/12067/)
=> Fixed non-x86 debian builds of php (3.21)

ci/cfengine-build-host-setup.cf
=> Added github known_hosts for build host setup policy

ci/cfengine-build-host-setup.cf
Also alphabetized packages for easier maintenance.
Ticket: none
=> Added parallel package for containers build hosts

ci/linux-install-jdk21.sh
=> linux-install-jdk21.sh: Fixed bad checksum

build-scripts/functions
- **build-scripts/functions: lowercase severity text**
=> build-scripts/functions: Changed logging function severity text to all lowercase

ci/cfengine-build-host-setup.cf
=> Added exception for sles_15 in build host policy regarding tricky ncurses-devel package which requires a downgrade currently

build-scripts/get_labels_expr.py
=> get_labels_expr.py: formatted with black

build-scripts/functions
=> functions: Documented function generate_chroot_transfer_script()

packaging/common/cfengine-hub/postinstall.sh
Ticket: ENT-11117
ChangeLog: none
together: https://github.com/cfengine/mission-portal/pull/2865
=> ENT-11117: Added post install command to migrate CMDB configs

ci/create-revisions-file.sh
Also refactored how we find the upstream name from jenkins environment variables.
Ticket: ENT-12581
=> Fixed difference of branch name in documentation without .x suffix and other repositories with .x suffix

build-scripts/prepare-testmachine-chroot
=> ENT-13189: Added root prefix when creating essential directories in chroot

.github/workflows/format.yml, build-scripts/compile-options, build-scripts/detect-environment, build-scripts/functions
- **format.yml: added workflow to format shell scripts**
- **compile-options: added missing shebang to files**
=> ENT-12601: Added workflow to automatically format shell scripts

.github/workflows/format.yml, Makefile, build-scripts/prepare-testmachine-chroot, user-scripts/format-shell-scripts.sh
=> Fixed prepare-testmachine-chroot script quoting so that dd does not create an infinitely sized /dev/urandom in chroot cases

build-scripts/install-dependencies
=> Removed bad quoting preventing word splitting

build-scripts/transfer-to-buildmachine
- **transfer-to-buildmachine: decreased verbosity of script**
- **transfer-to-buildmachine: documented script**
- **transfer-to-buildmachine: added log message to aid in debugging**
Build (no tests):
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12713)](https://ci.cfengine.com/job/pr-pipeline/12713/)
=> ENT-12600: transfer-to-buildmachine: documented and refactored script

build-scripts/transfer-to-testmachine
- **transfer-to-testmachine: documented script**
- **transfer-to-testmachine: reduced verbosity of script**
- **transfer-to-testmachine: added log messages to aid debugging**
=> ENT-12600: transfer-to-testmachine: documented & refactored script

ci/quick-install-cfengine-enterprise.sh.sha256
This is in conjunction with another PR to change the script.
Ticket: ENT-13247
=> Updated checksum for quick install script in build host scripts
