- build-scripts/prepare-testmachine-chroot
- build-scripts/test-on-testmachine
Note that we consider failure to clean up after yourself an error.
The chroot survives it just fine, but we still want the tests to
behave nicely so that it doesn't happen when you run them locally
either.
> Redmine #6818: Detect and clean up lingering processes in chroot.

- build-scripts/detect-environment
- build-scripts/functions
- build-scripts/prepare-testmachine-chroot
- build-scripts/test-on-testmachine
- deps-packaging/libacl/cfbuild-libacl.spec
- deps-packaging/libacl/debian/rules
- deps-packaging/libattr/cfbuild-libattr.spec
- deps-packaging/libattr/debian/rules
- deps-packaging/libgcc/solaris/build
- deps-packaging/libiconv/solaris/build
- deps-packaging/libxml2/hpux/build
- deps-packaging/libxml2/solaris/build
- deps-packaging/lmdb/cfbuild-lmdb.spec
- deps-packaging/lmdb/hpux/build
- deps-packaging/lmdb/solaris/build
- deps-packaging/openldap/solaris/build
- deps-packaging/openssl/solaris/build
- deps-packaging/pcre/solaris/build
- deps-packaging/pkg-build-solaris
- deps-packaging/pkg-get-src
- deps-packaging/postgresql-hub/source
- deps-packaging/postgresql/cfbuild-postgresql.spec
- deps-packaging/postgresql/solaris/build
- deps-packaging/postgresql/source
- deps-packaging/redis/cfbuild-redis.spec
- deps-packaging/sasl2/solaris/build
- deps-packaging/zlib/solaris/build
Various fixes for Solaris. This was used to build the 3.6.4 package so the commit IDs should not be altered. If fixes are needed they should be put on top.
> Solaris build fixes

- build-scripts/detect-environment
- build-scripts/functions
- build-scripts/prepare-testmachine-chroot
- build-scripts/test-on-testmachine
- deps-packaging/libacl/cfbuild-libacl.spec
- deps-packaging/libacl/debian/rules
- deps-packaging/libattr/cfbuild-libattr.spec
- deps-packaging/libattr/debian/rules
- deps-packaging/libgcc/solaris/build
- deps-packaging/libiconv/solaris/build
- deps-packaging/libxml2/hpux/build
- deps-packaging/libxml2/solaris/build
- deps-packaging/lmdb/cfbuild-lmdb.spec
- deps-packaging/lmdb/hpux/build
- deps-packaging/lmdb/solaris/build
- deps-packaging/openldap/solaris/build
- deps-packaging/openssl/solaris/build
- deps-packaging/pcre/solaris/build
- deps-packaging/pkg-build-solaris
- deps-packaging/pkg-get-src
- deps-packaging/postgresql-hub/source
- deps-packaging/postgresql/cfbuild-postgresql.spec
- deps-packaging/postgresql/solaris/build
- deps-packaging/postgresql/source
- deps-packaging/redis/cfbuild-redis.spec
- deps-packaging/sasl2/solaris/build
- deps-packaging/zlib/solaris/build
Various fixes for Solaris. This was used to build the 3.6.4 package so the commit IDs should not be altered. If fixes are needed they should be put on top.
> [3.6.x] Solaris build fixes

- build-scripts/compile-options
The LD_LIBRARY_PATH points to Java libraries, and for some reason the
OpenLDAP build thinks it needs the libnet library from there, which is
of course completely wrong, since it is a Java library. Nevertheless
it tries to depend on it, which then causes problems when trying to
run the binary.
> Fix Solaris binaries not finding the libnet library.

- build-scripts/package
- deps-packaging/pkg-build-rpm
It seems this never worked right for more than one "--define" arguments
in `$RPMBUILD_OPTIONS`. However it only got exposed after the
"debug_and_release kill" commit, that cause more complex rpmbuild
commands to be needed.
> Fix quoting of rpmbuild command line.

- build-scripts/install-dependencies
- deps-packaging/pkg-cache
For reference, at the time of writing more than 200 packages are
present on the AIX build slave. Better to save some space.
> Add autopruning of old package dependencies.

- build-scripts/compile-options
Not urgent, since the package builds specify hub/agent specifically, but good to have in the testing pipeline so it tests the right type of agent.
> Make sure well known hub platforms default to hub in the test builds.

- contrib/cf-deb-dep/cfbuild-dev.ctl
- contrib/cf-deb-dep/cfbuild-native.ctl
We do use the system library for this (it's too tied to login
infrastructure), so we don't repack it; thus a repacking developer
does need it, as much as the native developer does.
> Moved libpam-dev from native to dev.

- build-scripts/test-on-testmachine
Most platforms print the PIDs on stdout, and decorative characters on
stderr. Together they look like nicely formatted output when printed
on the console, but it also allows you to pipe only the PIDs somewhere
else. However, RHEL4 prints everything on stdout, so we need to filter
out the superflous characters there. All we need are numbers and the
spaces between them, so reject everything else.
> Fix fuser output being misinterpreted on RHEL4.

- packaging/common/cfengine-hub/postinstall.sh
This is for the /opt/cfengine/masterfiles.git repo that is created when a hub is first installed.
> Fix .gitignore for cf_promises_* in OOTB git repo for enterprise hubs

- build-scripts/detect-environment
Now that Jessie has been released (as 8.0), we need to be able to recognise the new testing version.
> Teach detect-environment about Debian stretch (new testing, shall be 9.0)

- deps-packaging/postgresql-hub/postgresql.conf.cfengine
Enable constraint_exclution for partitions to prevent queries pn master table to touch all child tables instead only relevant ones.
> Add timestamp for postgres log messages.

- packaging/common/cfengine-hub/postinstall.sh
On looking at the installed file on my Debian test machine, I found it
started with the -e we'd passed to echo to get it to honour the '\n'
that appear in what we're echoing.  It turns out bash's echo outputs a
'\n' as such unless given -e; while dash's echo interprets \n as a
newline without a -e and includes any -e passed to it as part of its
output.  So no single echo invocation works for both.  Break up the
lines into separate invocations of echo, bung them in a sub-shell and
drop the sub-shell's accumulated output into .gitignore
I still need to test this works as expected.
> Change the command to create Design Centre's .gitignore

- packaging/cfengine-nova/cfengine-nova.spec.in
as it seems RPM behaviour changed from RHEL4 to RHEL6.
> Explicitly set directory mode

- packaging/cfengine-nova-hub/debian/control
All Debian platforms which support the hub package (Debian 6 and
higher, as well as Ubuntu 10 and higher) need this library in order
to work. Debian 4 doesn't have the library, but we also don't build a
hub package for that platform.
> Redmine #7289: Add libltdl7 as a dependency to the hub package.

- deps-packaging/lmdb/debian/rules
The build slaves don't seem to need it, but I do on my machine.
> Fix SSIZE_MAX not being defined in certain MinGW versions.

- packaging/common/script-templates/deb-script-common.sh
Fixes CFEngine web service being launched in the wrong process group.
> Redmine #7335: Debian: Make sure systemd is used when it's supported.

- build-scripts/bootstrap-tarballs
- build-scripts/generate-source-tarballs
- build-scripts/unpack-tarballs
The first is supposed to run from the "bootstrap" jenkins job and create
the core and masterfiles tarballs, and delete the git-checked-out
directories.
The second is supposed to run in the next stage in each of the
buildslaves, and unpack the tarballs and symlink into the core/ and
masterfiles/ directories.
This way we have a separate tarball from the "bootstrap" slave suitable
for releasing, and we test in all platforms that the tarball is valid.
> Add build-scripts/bootstrap-tarballs and build-scripts/unpack-tarballs

- packaging/cfengine-nova/cfengine-nova.bff.sh
The directory is not cleaned, so each time we build a different
version we get a new package. This propogates all the way to the final
package directory, which is both confusing and potentially dangerous,
since someone may be tempted to download a package for a given version
that looks legitimate, but is in fact, an old/broken build.
> Redmine #6954: Prevent accumulation of unrelated AIX packages.

- build-scripts/package
- deps-packaging/pkg-build-solaris
There were in fact three separate issues at work to prevent symlinks
from reaching the package:
The first is the fact that Solaris' shell appears to return true for
the -f test, even if the file is actually a link. So we need to test
for a link first. This is the fix in pkg-build-solaris.
Secondly, cp does not preserve links unless -P is given, but -P is not
supported on Solaris 9, so instead we use rsync with the -l option.
And third, we were using `find -type f` to iterate through the package
candidate files, but this would not return links at all. We switch to
using the pkgproto tool directly instead, but this required some
restructuring because the directory cannot have any non-package files
when that command is invoked, or they will be included in the package
verbatim. Changed the …
> Redmine #7591: Fix Solaris pkgs contain dupl. files instead of links.

- build-scripts/bootstrap-tarballs
The problem is that a few select build targets are built even when
doing just "make dist". One example is the
tests/unit/init_script_test_helper, which is built because the test
shell script depends on it. This is no problem for the tarball,
because it won't be included, however when we afterwards copy the
workspace to the other build slaves, they will think that this target
was already built, and therefore it won't be rebuilt in the native
binary format.  Obviously a Solaris host won't be able to run a Linux
binary.
> Fix certain Linux build targets bleeding over into other build slaves.

- deps-packaging/apr-util/debian/rules
RPM spec file has the same hack removed some time now, and it's not obvious what purpose it serves.
> Remove sneaky build-time dependency of apr-util to apr

- packaging/common/cfengine-hub/postinstall.sh
In order to support CSV reports being send over HTTPS connection
we need to have cert.pem certificate in /var/cfengine/httpd/ssl.
This one is making a symbolic link in mentioned location to the
certificate file placed in /var/cfengine/httpd/ssl/.
Changelog: Fix exporting CSV reports through HTTPS. (Redmine #7267)
> Redmine #7267: Allow exporting CSV files over HTTPS.

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
Changelog: Change package modules permissions on hub package so that
hub can execute package promises. (Rednime #7602)
> Redmine #7602: Package modules not executable on hub

- packaging/common/cfengine-hub/postinstall.sh
This is for allowing downloading CSV reports in MP under HTTPS.
> Fix link MP certificate location.

- deps-packaging/libcurl/debian/rules
Otherwise the Windows 32-bit package does not install. To do this we
must also work around libtool not passing -static-* options to the
compiler like it should by using the CC variable.
> Fix libcurl compile by making sure it honors LDFLAGS.

- build-scripts/version
Core and Nova have been version locked to each other for a long time,
and this conflicts with autodetection of versions.
> CFE-2183: Remove Nova specific version.

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
- packaging/common/cfengine-hub/preremove.sh
- packaging/common/cfengine-non-hub/postinstall.sh
- packaging/common/cfengine-non-hub/preinstall.sh
- packaging/common/cfengine-non-hub/preremove.sh
- packaging/common/script-templates/script-common-header-last.sh
The script figures out whether it needs to start or stop anything, so
before we call it, we don't actually know whether we should output
such a message.
Fix by refactoring cf_console to do general redirection for all
commands, instead of just "echo". This way we can call the script with
messages directed to the console, instead of the log, where all the
rest of the message go.
> CFE-2359: Do not claim to start or stop CFEngine unless it's true.

- deps-packaging/php/0001-Revert-Fix-memory-leak-with-not-freeing-OpenSSL-erro.patch
- deps-packaging/php/cfbuild-php.spec
- deps-packaging/php/debian/rules
Both Curl and OpenSSL want to call this function, but it's only
allowed to call it once. This is a bug in PHP itself, so remove for
now. A memory leak in the cleanup is insignificant compared to a
crash.
> ENT-2724: Fix crash in PHP cleanup function.

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
Otherwise login to Mission Portal fails for platforms that don't have
it.
> ENT-2714: Add libtool-ltdl as RedHat package dependency.

- packaging/common/script-templates/script-common-header-last.sh
/var/log doesn't always exist on HP-UX.
> Fix error in package scripts when trying to redirect output on HP-UX.

- build-scripts/build-environment-check
- build-scripts/detect-environment
- build-scripts/functions
- build-scripts/install-dependencies
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
Accidental installation of libtool and related packages on our buildslaves led to our hub package gaining one dependency. This is a series of commits that ensures this won't happen in the future.
> ENT-2714 fix libltdl dependency

- packaging/cfengine-nova-hub/debian/control
> ENT-2714: Hub package no longer depends on libltdl.

- packaging/common/cfengine-hub/postinstall.sh
awk can find the appropriate line without using cat and grep.
> Change: Use fewer pipes to extract total memory

- build-scripts/detect-environment
It could not handle strings of the type:
'CentOS Linux release 7.2.1511 (Core) '
> Fix incorrect CentOS version detecton for newer OSes.

- build-scripts/functions
They contain a lot of weird stuff that can't be copied.
> Don't include Linux Container directories in chroot.

- build-scripts/detect-environment
> Fix version detection on Debian when encountering two digit numbers.

- build-scripts/compile-options
This fits Jenkins better, since we may use the same platform for
multiple roles.
Also, the hub will build on any modern Linux, so just assume that role
on any Linux platform when the Jenkins label is not in the
environment.
> Switch from OS based to environment based detection of package role.

- build-scripts/functions
We need to include them in the test chroot.
> Adapt to newer Linux distros having moved lock files to /run.

- build-scripts/detect-environment
Specifically for strings like:
'CentOS release 4.5 (Final)'
> Fix CentOS version detection.

- build-scripts/prepare-testmachine-chroot
It needs to add to the existing PATH, not just add it blindly. The
reason is that root has a different path than a user, and we will
need entries from both.
> When exporting environment to chroot, treat PATH specially.

- deps-packaging/pkg-cache
This way multiple build slaves can share the cache without fear of
overwriting each other's packages.
> Index the package cache by Jenkins node label.

- build-scripts/detect-environment
If CROSS_TARGET is already set in the environment it will take
precedence though.
> Detect cross compilation for Windows using Jenkins labels.

- build-scripts/package-msi
Wix tools have a ridiculously short maximum file length of 128
characters.  This is easily exceeded when Jenkins workspace paths are
involved. Luckily we can shortcut the paths by using Windows drive
letters to point to a directory closer to the source files. Wine will
automatically use the shortest one.
> Work around too long path lengths when packaging Windows MSI.

- build-scripts/prepare-testmachine-chroot
The default shell requires assignment, then export, not both at the
same time.
Also switch from bash to sh as the piping mechanism. More portable,
and we don't need bash here.
> Fix Solaris shell not accepting environment format when testing.

- build-scripts/prepare-testmachine-chroot
Apparently its sed doesn't handle '\n' characters in the script. Break
up the whole section instead, make it more readable, and use printf
for the final output.
> Fix Solaris choking on environment transfer.

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
The problem was that the initial population of the new database was
run before re-import of the database that was dumped from the old one.
The import script was not prepared for the database to already have
content. However the population scripts are prepared for this, since
this is what would happen if you upgraded between CFEngine versions
that run the same PostgreSQL version.
So the fix is to swap the order, run the import first. However, we
must take care to create the actual databases as well as the database
users first, since these are not covered by the import script.
Fix a couple of other minor things as well.
> ENT-2760: Enterprise: Fix Postgres database migration from 3.8- to 3.9+.

- build-scripts/version
When using AC_INIT to specify the version, the result in 'configure'
is slightly different, now having quotes around it.
> Fetch correct version from 'configure' even for new style AC_INIT.

- build-scripts/compile-options
- build-scripts/detect-environment
- deps-packaging/pkg-cache
This was happening because the NODE_LABELS variable contained all labels
that a particular node can get. Fixed by switching to the "label"
environment variable.
> INF-370: fix hub being built on agent nodes

- build-scripts/compile-options
Because all packages-* jobs come from the same upsteam job, they all have the "nova" directory. Thus auto-detection was building Enterprise packages everywhere.
Fixed by looking for a "JOB_NAME" environment variable that is usually
set by Jenkins.
> INF-370: Fix Community jobs building Enterprise packages

- packaging/common/cfengine-hub/postinstall.sh
redis-server needs to daemonize, otherwise non-systemd platforms will
hang when trying to launch it.
> ENT-2831: Fix bootstrap hanging on non-systemd platforms.

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
What would happen is that after an upgrade, particularly going from
pre-3.10 to 3.10.0+, the systemd files would change significantly, but
systemd would not pick this up. This would cause it to use the old
systemd units, which would launch the services using the init script.
This would place nearly all services under a single cgroup, instead of
in separate cgroups, which is the intention in 3.10. This is bad
enough on its own, but is rendered particularly troublesome because
PostgreSQL uses sudo to launch itself, and it would place itself in a
separate cgroup which is unmanaged by systemd, hence it could never be
killed afterwards, except manually.
We avoid all this by reloading the systemd unit files at the start of
the postinstall script, after the files have been updated, but before …
> CFE-2545: Fix services launching under wrong cgroup after upgrade.

- deps-packaging/pkg-cache
Also improved some logging messages.
> pkg-cache list: do not print literal '*' if the directory is empty.

- deps-packaging/README.md
- deps-packaging/openldap/mingw/debian/rules
- deps-packaging/openssl/cfbuild-openssl.spec
- deps-packaging/openssl/distfiles
- deps-packaging/openssl/solaris/build
- deps-packaging/pkg-get-src
* Update OpenSSL version. Actually not required for mingw compilation, but since build artifacts cache was accidentally [disabled](https://github.com/mendersoftware/jenkins-jobs/commit/b1676ddc23635730bedd25e33ecd3e752d334706) via Jenkins policy, it was breaking the build process.
* symlink a *.dll file to a folder where a test will find it
> INF-422: Mingw slaves not launching correctly

- packaging/common/cfengine-hub/postinstall.sh
Mission Portals application logs have moved from
/var/cfengine/httpd/htdocs/application/logs to
/var/cfengine/httpd/logs/application
> ENT-2758: Reloacte Mission Portal application logs

- packaging/common/cfengine-hub/postinstall.sh
This runs database migrations during post-install. Note, it always tries
to move forward (even though migrations support going backwards with
the "down" option). If a package is either upgraded or downgraded then
the migration runs. We don't explicitly support downgrading packages
currently so I believe this is OK even if not ideal.
> ENT-3129: Run database migrations during post-install

- deps-packaging/libcurl-hub/source
Just like we do for libcurl. RHEL4, RHEL5 are giving TLS errors for the
HTTPS upstream repository.
> Use an HTTP mirror for libcurl-hub.

- packaging/common/cfengine-hub/preinstall.sh
Take care to not purge the generated cf_robot.php and tmp which may
contain reports.
> ENT-3205: Purge previous versions htdocs on upgrade

- packaging/common/cfengine-hub/postinstall.sh
After package upgrade a bunch of old and new files are mixed up in
htdocs directory, for example old and new Code Igniter versions coexist.
Unfortunately it's not trivial to just delete the old files, because
they are manually copied after package installation, and workarounds are
messy because of the mess the hub package currently is (see ENT-3218).
> ENT-3205, ENT-3218: Warn that RPM hub package upgrade is unsupported

- build-scripts/autogen
Previously it was only noticed during the testing-enterprise-* job,
where the configure scripts actually run.
> Complain about version mismatch during bootstrap phase

- build-scripts/travis
Travis checks out with `--depth` parameter[1], which implies
`--single-branch`[2]. This confuses determine-version.py script, so we
need to convert the repo to normal one.
[1]: https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth
[2]: https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt
> unshallow repos

- build-scripts/travis
since new determine-version.py requires them
Maybe we should edit relevant script in core, too
> checkout branches instead of "unshallow" operation

- deps-packaging/openssl/source
Listed here: https://www.openssl.org/source/mirror.html
This is needed due to error in the current mirror - download fails (both with wget and with the browser)
> Switch to a working openssl mirror

- build-scripts/travis
We need to uninstall emacs* packages on Trusty (otherwise next apt-get command fails), but should not do it on Precise ('cause there is no such package)
> Make travis build script compatible both with Precise and Trusty

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
- packaging/common/cfengine-hub/preremove.sh
- packaging/common/cfengine-non-hub/postinstall.sh
- packaging/common/cfengine-non-hub/preremove.sh
- packaging/common/script-templates/deb-script-common.sh
- packaging/common/script-templates/rpm-script-common.sh
Older versions of systemd require the unit suffix to be provided when enabling
services. This change better supports older versions (like those from wheezy
backports).
> ENT-3325: Fix split service enablement on older versions of systemd

- build-scripts/travis
Also, ignore curl errors - it's a last command on thsi stage,
so even if it fails - it should not fail the build
> ENT-3277: Avoid printing secrets in log and fix curl command.

- deps-packaging/php/cfbuild-php.spec
- deps-packaging/php/debian/rules
This change increases the default memory_limit for php so that Mission Portal
works better with larger environments without altering default configuration.
> ENT-3391: Set default memory_limit for php to 256M

- deps-packaging/openssl/cfbuild-openssl.spec
ssl/openssl.cnf file is needed for CFEngine and should be also included in openssl packaging.
Other files (that are not needed) should be deleted from there.
> pack ssl/openssl.cnf, delete some other for openssl

- deps-packaging/postgresql-hub/postgresql.conf.cfengine
- packaging/common/cfengine-hub/preinstall.sh
Now the postgres socket permissions are only accessible by cfapache, cfpostgres,
and root.
> ENT-2746: Tighten postgres socket permissions

- packaging/common/cfengine-hub/preinstall.sh
Fixing a regression introduced in 01a7ba50c87c7ac8e5b2223c9895b032d6c0783b
> ENT-3613: cd to a readable dir before executing `pg_dump`

- packaging/common/cfengine-hub/postinstall.sh
Fixes permission issues - parent directory is root-only
Signed-off-by: Aleksei Shpakovskii aleksei.shpakovskii@cfengine.com
> ENT-3617: pipe *.sql files instead of reading them

- build-scripts/compile-options
For some reason, the AIX linker doesn't export the symbols
prefixed with underscore. In combination with how OpenSSL does
its magic with ASM the result is that OpenSSL fails to link.
We need to add one more explicit option to tell the linker to
export everything. Not sure if this is the best thing to do, but
it works.
> ENT-3595: Add one more extra option for the AIX linker

- packaging/common/cfengine-hub/postinstall.sh
We have policy in MPF to ensure this, but this change should result in having the proper permissions directly after package install/upgrade.
> ENT-3645: Ensure settings.ldap.php has the proper permissions after package install

- build-scripts/travis
@Lex-2008 turns out there is a perfectly suitable and easily available method for running the .test files: /usr/bin/prove! (provided by Perl where TAP format tests came from in the first place).
I ran through a debug session on travis and all seemed fine with this change.
> ENT-3525 fix reporting tests execution for travis

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-community/debian/cfengine-community.install
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install
- packaging/cfengine-nova/cfengine-nova.spec.in
- packaging/cfengine-nova/debian/cfengine-nova.install
- packaging/common/cfengine-hub/postinstall.sh
https://github.com/cfengine/core/pull/3086
https://github.com/cfengine/nova/pull/1152
https://github.com/cfengine/buildscripts/pull/359
> ENT-3726: Remove cf-consumer from packaging/buildscripts

- deps-packaging/php/cfbuild-php.spec
- deps-packaging/php/old-gcc-isfinite.patch
@vpodzime moved patch to proper location
@Lex-2008 skipped the upgrade to make this commit and our lives a bit more certain
will start a pr-pipeline build on rhel5 for hub now.
> ENT-3761: Fix php build for rhel5 due to isfinite reference

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
This ensures that if a user modifies php.ini locally, their changes will be preserved when they upgrade the package.
> ENT-3835 Treat php.ini as a config file by pacakge

- build-scripts/functions
failure, for example, in https://ci.cfengine.com/job/testing-enterprise-3.12.x/8/label=PACKAGES_sparc64_solaris_10/console:
```
00:25:19.609 rsync: mknod "/home/jenkins/testmachine-chroot/etc/svc/volatile/.inetd.uds" failed: Not owner (1)
00:25:19.639 skipping non-regular file "etc/svc/volatile/repository_door"
00:25:19.639 skipping non-regular file "etc/svc/volatile/zonestat_door"
00:25:19.639 skipping non-regular file "etc/svc/volatile/netcfg/netcfgd_door"
00:27:17.020 rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.8]
00:27:17.054 + ret=23
00:27:17.054 + [ -f /home/jenkins/stop_slave ]
00:27:17.054 + exit 23
```
> INF-402: exclude from copying file which can't be copied

- deps-packaging/git/cfbuild-git.spec
- deps-packaging/git/debian/rules
These two ./configure options are:
--with-gitconfig=VALUE  Use VALUE instead of /etc/gitconfig as the global
git configuration file. If VALUE is not fully
qualified it will be interpreted as a path relative
to the computed prefix at runtime.
--with-gitattributes=VALUE
Use VALUE instead of /etc/gitattributes as the
global git attributes file. If VALUE is not fully
qualified it will be interpreted as a path relative
to the computed prefix at runtime.
so they should be file paths, not directories. New versions of
git are sensitive to this difference.
Ticket: ENT-3818
> Use proper gitconfig and gitattributes file paths when building git

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
Otherwise they may end up being copied over to htdocs together
with the new files because the postinstall.sh script is run when
*both* the old package and the new package are installed.
> ENT-3898: Move old shared/GUI files aside during upgrade 

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
Otherwise they may end up being copied over to htdocs together
with the new files because the postinstall.sh script is run when
*both* the old package and the new package are installed.
(cherry picked from commit d10682132702d032f4c4d0987234c6732357611a)
> ENT-3898: Move old shared/GUI files aside during upgrade

- packaging/common/cfengine-hub/postinstall.sh
Because cf-runalerts.service executes this script.
(cherry picked from commit f999f8dfab5bd8a0cbb4bd7f870ae56a2e9ab624)
> ENT-3921: Make runalerts.php executable.

- build-scripts/labels.txt
Solaris 9 is not a supported system for future releases.
> Disable Solaris 9 builds on master

- deps-packaging/lmdb/0007-Do-not-put-functions-into-a-separate-text-section-on.patch
Somehow this breaks things horribly and such functions seem to
collide in address space with 'glibc' functions. Segfaults then
happen and backtraces are totally weird.(*)
(*) at least on RHEL 6.9, gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
> lmdb: Do not put functions into a separate text section on PPC64

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
- packaging/common/cfengine-non-hub/preinstall.sh
- packaging/common/script-templates/script-common.sh
We shouldn't blindly start all our daemons/services after package
upgrade, but rather honor the original/pre-upgrade state.
Changelog: Only start previously running processes on package upgrade
> ENT-3972: Save and restore state on package upgrade

- packaging/common/cfengine-hub/preinstall.sh
If 'pg_ctl stop -m smart' fails, it means that there are some
clients that are not properly terminating their sessions. Using
'pg_ctl stop -m fast' shuts down such sessions. That may
potentially be unsafe, but the only clients of our PostgreSQL are
our components -- namely Redis, cf-hub and Mission Portal. All of
these should be dead by the time we stop PostgreSQL so it's safe
to terminate any sessions they may have left open.
> Try harder to stop PostgreSQL on upgrades

- packaging/common/script-templates/script-common.sh
The enterprise init script checks is was called from an expected
place (the core init script or state restore) so we need to tell
it that we are restoring state in scriptlets.
> Set the flag for the enterprise init script in state restore

- packaging/common/script-templates/script-common.sh
The enterprise init script checks is was called from an expected
place (the core init script or state restore) so we need to tell
it that we are restoring state in scriptlets.
(cherry picked from commit 43a00130b0a4d19213853689ee7cc54b6d73e8c6)
> [3.12.x] Set the flag for the enterprise init script in state restore

- packaging/common/cfengine-hub/preinstall.sh
If 'pg_ctl stop -m smart' fails, it means that there are some
clients that are not properly terminating their sessions. Using
'pg_ctl stop -m fast' shuts down such sessions. That may
potentially be unsafe, but the only clients of our PostgreSQL are
our components -- namely Redis, cf-hub and Mission Portal. All of
these should be dead by the time we stop PostgreSQL so it's safe
to terminate any sessions they may have left open.
(cherry picked from commit 0c3182c65c1764aadf878cf881b9906e9100e1fa)
> [3.12.x] Try harder to stop PostgreSQL on upgrades

- packaging/cfengine-nova/cfengine-nova.wxs
If an existing key is present during pacakge install we should not try
to re-generate a new one. Trying to generate a new key when one already
exists will fail, and that will cause the package to not finish
installing correctly.
> ENT-3715 Only attempt to generate key during install if not present on windows

- packaging/common/cfengine-hub/preinstall.sh
If 'apachectl stop' finishes with exit code 0, but something is
still listening on the HTTP(S) port(s), it's worth it to try and
give 'httpd' some more time to finish terminating properly before
just giving up.
(cherry picked from commit c0af01d63081f9c529d1c981b2b8a8b2cf0c90cd)
> [3.12.x] Give httpd time to stop listening on 80/443 on upgrades

- deps-packaging/postgresql-hub/postgresql.conf.cfengine.patch
If the group ownership is not correct on the socket file, then cfapache will not
be able to connect to the cfsettings database and user authentication will fail.
> ENT-4170 Explicitly set unix_socket_group

- packaging/common/cfengine-hub/preinstall.sh
3.7.x has broken detection of the PostgreSQL status and
'postgres' is always reported as 'not running'. Thus when we
capture the pre-upgrade state of runnig processes, PostgreSQL is
missing there and as a consequence it is not started when the
upgrade is finished.
To workaround this, let's assume that PostgreSQL is running on
3.7.x if cf-hub is also running.
Ticket: ENT-4082
> Upgrade: assume PostgreSQL is running on 3.7.x if running cf-hub

- packaging/common/cfengine-hub/preinstall.sh
3.7.x has broken detection of the PostgreSQL status and
'postgres' is always reported as 'not running'. Thus when we
capture the pre-upgrade state of runnig processes, PostgreSQL is
missing there and as a consequence it is not started when the
upgrade is finished.
To workaround this, let's assume that PostgreSQL is running on
3.7.x if cf-hub is also running.
Ticket: ENT-4082
(cherry picked from commit 5f0f0d691b41c0035d6021cb240ad083c49ad313)
> 3.12.x: Upgrade: assume PostgreSQL is running on 3.7.x if running cf-hub

- packaging/common/script-templates/script-common.sh
On older versions this may be the only systemd service running,
especially on the non-hub systems. So when saving the pre-upgrade
state, we need to capture the state of this service too.
Also drop unnecessary use of 'grep' and just use two commands
for 'sed'.
Ticket: ENT-4082
> Capture the state of the cfengine3.service too

- packaging/common/script-templates/script-common.sh
When saving state we are extracting names of CFEngine services
that are running. The recognized sevices are the ones starting
with the 'cf-' prefix and the 'cfengine3.service'. Everything
else has to be ignored, otherwise the 's//' sed command fails and
we get full lines from the 'systemct list-units' output in the
state snapshot which is supposed to only list the running
services and nothing else.
Ticket: ENT-4082
> Get running services from lines matching exactly what we expect

- packaging/common/cfengine-hub/postinstall.sh
This file defines access control for PostgreSQL and must be
preserved on upgrade. It may be granting extra access (e.g. in
the HA setup), but it may also be blocking some of the defaults.
> ENT-4231: Preserve the 'pg_hba.conf' file on upgrades

- packaging/common/script-templates/script-common.sh
Some platforms don't have this fancy feature of their 'sed'
tool. It's okay to use it on the systemd-based platforms though,
these are new enough.
> CFE-2949: Do not use '-r' with 'sed' when saving state on upgrade

- packaging/common/script-templates/script-common.sh
Some platforms don't have this fancy feature of their 'sed'
tool. It's okay to use it on the systemd-based platforms though,
these are new enough.
(cherry picked from commit ad3c50df7dcb02724af4a4746c24e27046a20858)
> [3.12.x] CFE-2949: Do not use '-r' with 'sed' when saving state on upgrade

- packaging/common/script-templates/script-common.sh
Some platforms don't have this fancy feature of their 'sed'
tool. It's okay to use it on the systemd-based platforms though,
these are new enough.
(cherry picked from commit ad3c50df7dcb02724af4a4746c24e27046a20858)
> [3.10.x] CFE-2949: Do not use '-r' with 'sed' when saving state on upgrade

- packaging/common/cfengine-hub/preinstall.sh
Having the same check in two places is error prone to not
updating both places with changes. Exactly as it happened
recently in 7c515c832b.
Doing the check once and storing the result is better and will
also make it easier to change the check to something more complex
doing decisions on version differences and not hardcoded values.
> Refactor how we check if PostgreSQL should be prepared for migration

- packaging/common/script-templates/rpm-script-common.sh
The 'cfengine3' init script is under /etc/rc.d/init.d on AIX. We
already have functions for these tweaks, let's just use them
more.
Ticket: ENT-4305
Changelog: Fix running cfengine3 init script in AIX RPMs
(cherry picked from commit f30d69e2e0ce203d7ced2777fa97ff3e2c53d740)
> [3.12.x] Fix platform_service() on AIX in RPM packages

- deps-packaging/php/cfbuild-php.spec
- deps-packaging/php/debian/rules
New Export/Import tooling requires phar
> ENT-4126: Set phar read only off for PHP

- deps-packaging/php/cfbuild-php.spec
- deps-packaging/php/debian/rules
New Export/Import tooling requires phar
(cherry picked from commit 8fe7edac968effd5e02d4c29c8d29e036985d216)
> ENT-4126: Set phar read only off for PHP (3.12)

- build-scripts/labels.txt
The Solaris 10 zone is heavily unreliable and is causing builds
to fail almost every day. It's better to have green builds and
only make sure everything is fine on Solaris 10 before the
release. Note that we are still running tests on Solaris 11
SPARC64.
> Disable pr-pipeline builds on Solaris 10 SPARC64

- build-scripts/labels.txt
See commit message(s) for details.
> Disable Solaris 9 and 10 SPARC64 on pr-pipeline

- build-scripts/get_labels_expr.py
This will allow us to split the full run of tests into two jobs
-- one for non-exotic platforms and one for exotic platforms. We
can then treat their results, stability issues,... differently.
> Add an option to get ONLY exotic labels with get_labels_expr.py

- build-scripts/get_labels_expr.py
We need to respect the original list of labels not just take the
exotics. There might be some exotics that are not in the full
list of labels which thus should be filtered out.
Also make the logic clearer by using sets and set operations.
> Fix getting configuration filter for exotics only

- packaging/common/script-templates/script-common-header-last.sh
To ensure that we do not accidentally leak sensitive information, we set the
umask so that new files are only readable by the owner.
> ENT-4506 New files created during package changes are restricted

- packaging/common/script-templates/script-common-header-last.sh
The log is produced on both hub and client installations. Instead
of adding complexity to differentiate between the cases, let's
just use a neutral filename.
Ticket: ENT-4564
> Drop 'Hub' from the installation log filename

- deps-packaging/openssl/0001-cfi-build-fixes-in-x86-64-ghash-assembly.patch
- deps-packaging/openssl/cfbuild-openssl.spec
- deps-packaging/openssl/debian/rules
Upstream has this fix, but it didn't make it to OpenSSL-1.1.1b so
we have to apply it ourselves.
> Add a patch fixing x86_64 assembly in OpenSSL

- build-scripts/install-dependencies
Otherwise it fails to load the POSIX.pm module which loads the
POSIX.so shared object and fails to find some standard C
functions.
Ticket: ENT-4659
> Add some flags for building Perl on AIX 7

- deps-packaging/libyaml/debian/cfbuild-libyaml-devel.install
- deps-packaging/libyaml/debian/cfbuild-libyaml.install
If it's part of the -devel package it is not going to end up in
the cfengine package because we only install the -devel packages
for the building phase and then uninstall them before
packaging. Only the non-devel packages remain installed for the
packaging phase and thus only their contests are included in the
final cfengine package.
Ticket: CFE-3065
> Package libyaml.so as part of the cfbuild-libyaml package

- packaging/common/script-templates/script-common-header-last.sh
There is no root group on aix hosts, instead we should use a group that exists
by default.
The following accounts are predefined in the operating system:
- adm
The adm user account owns the following basic system functions:
- Diagnostics, the tools for which are stored in the /usr/sbin/perf/diag_tool
directory.
- Accounting, the tools for which are stored in the following directories:
- /usr/sbin/acct
- /usr/lib/acct
- /var/adm
- /var/adm/acct/fiscal
- /var/adm/acct/nite
- /var/adm/acct/sum
- bin
The bin user account typically owns the executable files for most user
commands. This account's primary purpose is to help distribute the ownership
of important system directories and files so that everything is not owned
solely by the root and sys user accounts.
- daemon
The daemon user account …
> Set group ownership for install log to system on aix

- packaging/common/script-templates/script-common-header-last.sh
Introduced in d932325141c9353fe7691d7cefab8950bea10adf.
> Fixed syntax error in sh script header

- packaging/common/script-templates/script-common-header-last.sh
There is no root group on aix hosts, instead we should use a group that exists
by default.
The following accounts are predefined in the operating system:
- adm
The adm user account owns the following basic system functions:
- Diagnostics, the tools for which are stored in the /usr/sbin/perf/diag_tool
directory.
- Accounting, the tools for which are stored in the following directories:
- /usr/sbin/acct
- /usr/lib/acct
- /var/adm
- /var/adm/acct/fiscal
- /var/adm/acct/nite
- /var/adm/acct/sum
- bin
The bin user account typically owns the executable files for most user
commands. This account's primary purpose is to help distribute the ownership
of important system directories and files so that everything is not owned
solely by the root and sys user accounts.
- daemon
The daemon user account …
> ENT-4733 Set group ownership for install log to system on aix

- deps-packaging/README.md
Issue was that postgresql was named as "postgresql-hub" in buildscripts, but "postgresql" in readme
> Correct PostgreSQL version in dependency tables

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/script-templates/script-common.sh
backport of https://github.com/cfengine/buildscripts/pull/574 to 3.12.x branch
> ENT-4853 Wait for cf-postgresql service to be running before rotating keys - 3.12.x

- deps-packaging/openssl/mingw/debian/rules
We need it to be a Windows path. However, when building and
installing files, we need it to be a UNIX path (the build runs on
Debian). So let's just override the macro definition.
> Override OPENSSLDIR in mingw builds

- deps-packaging/php/cfbuild-php.spec
- deps-packaging/php/debian/rules
ChangeLog: Enable Zlib extension in PHP to support png images with alpa channel
> ENT-2828: Build PHP with --with-zlib option

- deps-packaging/lmdb/0001-Do-not-abort-if-a-user-define-assert-function-is-cal.patch
We want to have a chance to handle the failure gracefully.
(cherry picked from commit 5ab94702103e09dbee27e3c4a52445ee7220766d)
https://github.com/cfengine/core/pull/3827
https://github.com/cfengine/buildscripts/pull/615
> [3.12.x] Patch LMDB to not abort on assert failure

- packaging/cfengine-community/cfengine-community.spec.in
The RHEL 8 community packages need the SELinux policy module too
so we install it as part of `make install`. We then need to
include it in the `%files` section of the RPM SPEC so that it
gets into the RPM.
> Package the SELinux policy module in RHEL 8 agent community packages

- deps-packaging/lmdb/README.md
Additionally, added an rm command, which is useful when
regenerating the patch fiels from git log.
> Easier LMDB patch instructions for working with different tags (3.12)

- build-scripts/travis
runtests.sh looks at TRAVIS environment variable and if present then skips tests which don't currently work there: migration and generate since they have dependencies which are not met.
merge with https://github.com/cfengine/nova/pull/1510
> ENT-4754: Enabled nova repo to decide which tests to run

- build-scripts/package
Only coreos tarballs are modified here in the 3.12.x port of the
original commit because generic tarballs don't even have the safe
prefix from commit 631125b7cba here.
(cherry picked from commit 8dc9c707574f2caba6c763b135d513f27996097f)
Conflicts:
build-scripts/package
> ENT-4981 Add build number to coreos and generic tarballs

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
If some service is masked, for example, 'systemctl enable' would
fail on it. And since our scriptlets are using 'set -e', they
exit on every error. We need to disable this behavior for the
part doing 'systemctl enable' on our services.
Ticket: ENT-5188
Changelog: 'systemctl enable' failure no longer stops the postinstall package scripts
> Do not stop postinstall script if 'systemctl enable' fails

- packaging/common/cfengine-hub/postinstall.sh
Need to make this safer for cases where the target directory is
already present and has files.
Ticket: ENT-5255
merge together
https://github.com/cfengine/buildscripts/pull/661
https://github.com/cfengine/masterfiles/pull/1645
https://github.com/cfengine/mission-portal/pull/993
> ENT-5255 Made Mission Portal application log relocation more resilient

- build-scripts/bootstrap-tarballs
We need to run './configure' to be able to run 'make dist' to get
a tarball. And './configure' requires one of LMDB or TokyoCabinet
to be installed (inlc. devel files). But we might as well just
install 'liblmdb-dev' on our bootstrap machines and let the
defaults do their job.
> Do not use '--with-tokyocabinet=/usr' when building tarballs

- packaging/common/cfengine-hub/postinstall.sh
merge together
https://github.com/cfengine/buildscripts/pull/663
https://github.com/cfengine/mission-portal/pull/995
https://github.com/cfengine/masterfiles/pull/1657
> ENT-5255: Made Mission Portal application log relocation more resilient (3.15.x)

- packaging/common/cfengine-hub/postinstall.sh
merge together
https://github.com/cfengine/buildscripts/pull/662
https://github.com/cfengine/masterfiles/pull/1656
https://github.com/cfengine/mission-portal/pull/994
> ENT-5255: Made Mission Portal application log relocation more resilient (3.12.x)

- packaging/common/cfengine-hub/postinstall.sh
There is a new 'inventory_variables_refresh' task introduced in
cfengine/mission-portal@d2550582. We no longer need to do full
inventory refresh.
Ticket: ENT-4864
> Adapt inventory refresh in the postinstall script

- deps-packaging/postgresql/cfbuild-postgresql.spec
- deps-packaging/postgresql/debian/rules
- deps-packaging/postgresql/pg_hba.conf.sample.patch
- deps-packaging/postgresql/postgresql.conf.cfengine.patch
- deps-packaging/postgresql/postgresql.conf.sample.patch
- Removed executable bit from unix socket
- Removed local TCP access rules
Ticket: ENT-2747
https://github.com/cfengine/buildscripts/pull/668
cfengine/nova#1585
cfengine/mission-portal#999
> ENT-2747/master: Tighten Postgresql access permissions

- deps-packaging/postgresql/cfbuild-postgresql.spec
- deps-packaging/postgresql/debian/rules
- deps-packaging/postgresql/pg_hba.conf.sample.patch
- deps-packaging/postgresql/postgresql.conf.cfengine.patch
- deps-packaging/postgresql/postgresql.conf.sample.patch
- Removed executable bit from unix socket
- Removed local TCP access rules
Ticket: ENT-2747
(cherry picked from commit dfca1ffde2953db4b70bd7ba0d3bdcce201eb282)
https://github.com/cfengine/buildscripts/pull/680
https://github.com/cfengine/mission-portal/pull/1025
https://github.com/cfengine/nova/pull/1608
> Tighten Postgresql access permissions (3.15.x)

- deps-packaging/postgresql/cfbuild-postgresql.spec
- deps-packaging/postgresql/debian/rules
- deps-packaging/postgresql/pg_hba.conf.sample.patch
- deps-packaging/postgresql/postgresql.conf.cfengine.patch
- deps-packaging/postgresql/postgresql.conf.sample.patch
- Removed executable bit from unix socket
- Removed local TCP access rules
Ticket: ENT-2747
(cherry picked from commit dfca1ffde2953db4b70bd7ba0d3bdcce201eb282)
https://github.com/cfengine/buildscripts/pull/681
https://github.com/cfengine/mission-portal/pull/1026
https://github.com/cfengine/nova/pull/1609
> Tighten Postgresql access permissions (3.12.x)

- packaging/common/cfengine-hub/postinstall.sh
The default timeout for stopping PostgreSQL with '-m smart'
(which tries to wait for connections to terminate) is 60
seconds. For some reason that is not always enough in the hub
postinstall scriptlet. So let's give it 120 seconds and fall back
to '-m fast' which terminates the connections (gracefully).
> Fall back to 'pg_ctl stop -m fast' if '-m smart' fails

- packaging/common/cfengine-hub/postinstall.sh
For some reason PostgreSQL fails to stop with '-m smart' (which
tries to wait for connections to be terminated) in the hub
postinstall scriptlet. So let's fall back to '-m fast' which
terminates the connections (gracefully).
(cherry picked from commit 5f01f5ca6ab671cf2d94d5e58a2725b09466446d)
> [3.15.x] Fall back to 'pg_ctl stop -m fast' if '-m smart' fails

- packaging/common/cfengine-hub/postinstall.sh
For some reason PostgreSQL fails to stop with '-m smart' (which
tries to wait for connections to be terminated) in the hub
postinstall scriptlet. So let's fall back to '-m fast' which
terminates the connections (gracefully).
(cherry picked from commit 5f01f5ca6ab671cf2d94d5e58a2725b09466446d)
> [3.12.x] Fall back to 'pg_ctl stop -m fast' if '-m smart' fails

- packaging/common/script-templates/script-common.sh
If a service or process fails to start in
restore_cfengine_state() we should continue and attempt to start
the other services/processes from the saved state and just report
the failure.
Ticket: ENT-5352
> Ignore failures in restore_cfengine_state() in scriptlets

- packaging/common/cfengine-hub/postinstall.sh
This directory is used by HA setups for speeding up recovery and
re-synchronizations. If it existed before the upgrade, it should
be recreated after it.
Ticket: ENT-5352
> Preserve state/pg/data/pg_arch directory on upgrades

- packaging/common/cfengine-hub/postinstall.sh
This directory is used by HA setups for speeding up recovery and
re-synchronizations. If it existed before the upgrade, it should
be recreated after it.
Ticket: ENT-5352
(cherry picked from commit 2a04956fda7dfb608734b3ae03e8de5fccfdc49b)
> [3.12.x] Preserve state/pg/data/pg_arch directory on upgrades

- packaging/common/cfengine-hub/postinstall.sh
This directory is used by HA setups for speeding up recovery and
re-synchronizations. If it existed before the upgrade, it should
be recreated after it.
Ticket: ENT-5352
(cherry picked from commit 2a04956fda7dfb608734b3ae03e8de5fccfdc49b)
> [3.15.x] Preserve state/pg/data/pg_arch directory on upgrades

- packaging/common/cfengine-hub/postinstall.sh
chmod 700 on $DCWORKDIR causes problems with Federated Reporting
cftransport user ssh permissions.
Ticket: ENT-5438
> Fix permissions on /opt/cfengine for FR cftransport user

- deps-packaging/README.md
- deps-packaging/openssl/cfbuild-openssl.spec
- deps-packaging/openssl/distfiles
Hopefully this fixes some of the 404 errors we've seen.
> Updated openssl 1.1.1d -> 1.1.1f (3.12)

- build-scripts/bootstrap-tarballs
We started to fetch JS dependencies from NPM (https://www.npmjs.com/) and we need to install them in bootsrap job
Ticket: ENT-5458
> Install JavaScript dependencies in bootstrap job

- build-scripts/bootstrap-tarballs
So that the tarballs (some of which we also release) can have
proper names and version information.
Ticket: ENT-5429
https://github.com/cfengine/masterfiles/pull/1737
https://github.com/cfengine/buildscripts/pull/726
> Make sure version information is available when building tarballs

- build-scripts/bootstrap-tarballs
So that the tarballs (some of which we also release) can have
proper names and version information.
Ticket: ENT-5429
(cherry picked from commit 2169d9a3b5dd1f5dc53d659371406a06cfaf7fae)
> [3.15.x] Make sure version information is available when building tarballs

- build-scripts/bootstrap-tarballs
So that the tarballs (some of which we also release) can have
proper names and version information.
Ticket: ENT-5429
(cherry picked from commit 2169d9a3b5dd1f5dc53d659371406a06cfaf7fae)
> [3.12.x] Make sure version information is available when building tarballs

- build-scripts/bootstrap-tarballs
- build-scripts/travis
Jquery UI grunt tasks miss images copying to dist and images are required to be into dist in css styles
> Copied jquery-ui images to dist directory

- build-scripts/functions
The new IBM CECC VMs have GCC 8 as the default compiler
(yum install gcc), but it is broken or at least doesn't work
properly with our specific codebase because it produces binaries
that fail in weird ways. Thus we need to use GCC 6 (from the
'gcc6' package), but that is installed under a non-standard path
which we thus need to add to $PATH for things to work.
Ticket: ENT-5418
> Use GCC 6 on new AIX 7.1 VMs

- deps-packaging/php/cfbuild-php.spec
- deps-packaging/php/debian/rules
mbstring functions are required in PHP dependencies.
> Enabled mbstring PHP extension

- build-scripts/compile-options
- deps-packaging/libcurl/cfbuild-libcurl.spec
- deps-packaging/openldap/cfbuild-openldap.spec
- packaging/cfengine-nova/cfengine-nova.spec.in
RHEL 8 version of OpenSSL ships with a downstream patch that adds
the EVP_KDF API which is not part of any stable release of
OpenSSL yet. This new API is required by some of the PAM modules
commonly installed on RHEL 8 systems and is thus required if we
want to use PAM from CFEngine binaries (for 'users'
promises). Instead of shipping our own version of OpenSSL with a
similar big EVP_KDF patch like Red Hat does, let's use their
version of OpenSSL which is definitely installed on every RHEL 8
system (required by many core components).
Ticket: ENT-5564
Changelog: RHEL 8 CFEngine packages now rely on system OpenSSL libraries
(cherry picked from commit 3a3ad02670d397a6b94a3960b1266299a3ad1a4c)
> [3.12.x] Use system-provided OpenSSL on RHEL 8

- build-scripts/compile-options
- deps-packaging/libcurl/cfbuild-libcurl.spec
- deps-packaging/openldap/cfbuild-openldap.spec
- packaging/cfengine-nova/cfengine-nova.spec.in
RHEL 8 version of OpenSSL ships with a downstream patch that adds
the EVP_KDF API which is not part of any stable release of
OpenSSL yet. This new API is required by some of the PAM modules
commonly installed on RHEL 8 systems and is thus required if we
want to use PAM from CFEngine binaries (for 'users'
promises). Instead of shipping our own version of OpenSSL with a
similar big EVP_KDF patch like Red Hat does, let's use their
version of OpenSSL which is definitely installed on every RHEL 8
system (required by many core components).
Ticket: ENT-5564
Changelog: RHEL 8 CFEngine packages now rely on system OpenSSL libraries
(cherry picked from commit 3a3ad02670d397a6b94a3960b1266299a3ad1a4c)
> [3.15.x] Use system-provided OpenSSL on RHEL 8

- build-scripts/travis
Cherry-pick to bring 3.15.x up to date with master, since this part looked suspicious. On 3.15.x, `cf-secret` path was not specified in argument to testall, while on master, it didn't need to be, because it's using bindir instead.
> Travis: Attempt to fix broken 3.15.x builds

- build-scripts/functions
This can speed up the compilation process quite a bit on our
semi-persistent build machines.
> Use ccache if available

- deps-packaging/libcurl-hub/source
- deps-packaging/libcurl/source
Because the one we used is down
> Use official mirror for curl

- build-scripts/unpack-tarballs
Issue was that sometimes build aborted on one of following lines with
'ln: core exists' error. Assuming that it's because `rm` command left it behind,
let's help it by elevating `rm`'s priviledges, and printing more meaningful
error message if it fails, together with list of items if these dirs to aid
debugging this issue should it appear again.
----
#
> ENT-4074 Better delete dirs and abort if it didn't succeed

- build-scripts/labels.txt
- deps-packaging/libcurl-hub/cfbuild-libcurl-hub.spec
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/postremove.sh
TODO:
https://github.com/cfengine/buildscripts/pull/771
https://github.com/cfengine/core/pull/4317
> RHEL 8 hub

- packaging/common/cfengine-hub/postinstall.sh
They may have terminated in the meantime which is a good thing.
Ticket: ENT-6103
> Keep going if 'kill' fails on httpd processes left behind

- build-scripts/unpack-tarballs
This is a suggested solution to https://tracker.mender.io/browse/ENT-4074 "ln: core exists error in jenkins".
Probable issue was that `rm -rf core/` does not delete 'core' itself if it's a symlink.
Also rework debug output slightly.
> ENT-4074 Delete also symlinks

- deps-packaging/lmdb/cfbuild-lmdb.spec
- deps-packaging/lmdb/distfiles
- deps-packaging/lmdb/source
For an unknown reason, 0.9.26 causes a spurious failure during
bootstrap on Ubuntu 14 hubs.
> Revert LMDB back to version 0.9.24

- README.md
3.12.x commits:
3ac208b764e26e9571029e51d8da73cf95a6296e Upgrade rsync from 3.1.3 to 3.2.3 and migrate from ibiblio mirror to samba.org
b3804777ce3785f1d393bfeafc35ec7b73f3bee9 Update LMDB from 0.9.24 to 0.9.26 and migrate from github to gitlab.
82d9ff642869cc0ca6296f02c9cabe02a1d2cfc8 Update libcurl from 7.70.0 to 7.72.0
e24f8f167e380e1df47903444e0d10c1eb025686 Update php from 7.2.30 to 7.2.34
e82fa70d452eb510b04aa6321b9a7dd061d94bc6 Update postgresql from 10.12 to 10.14
ed77e79aed9e07a34082fe6a3e047f7b41f561f0 Update git from 2.26.2 to 2.28.0
a8e3170d867ce29f92f7683f7202498a66ae04c0 Update apache from 2.4.43 to 2.4.46
4713657bd7369f6804fed7e48c3b35af57b1c021 Update libcurl-hub from 7.70.0 to 7.72.0
fc6b4268fa68ba2172f2728c8a2e1f497ee45555 Update openldap from 2.4.50 to 2.4.53 …
> Updated dependency markdown tables

- deps-packaging/apache/httpd.conf
Merge together: https://github.com/cfengine/masterfiles/pull/1909
Ticket: ENT-6783
> ENT-6783/master: Disabled TLSv1 by default for Mission Portal's web server

- deps-packaging/apache/httpd.conf
Ticket: ENT-6783
(cherry picked from commit 1447ed7516eef3629b3295dbb5932e24045bcc1a)
> ENT-6783/3.15.x: Disabled TLSv1 by default for Mission Portal's web server

- deps-packaging/apache/httpd.conf
Ticket: ENT-6783
(cherry picked from commit 1447ed7516eef3629b3295dbb5932e24045bcc1a)
> ENT-6783/3.12.x: Disabled TLSv1 by default for Mission Portal's web server

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
merge together: https://github.com/cfengine/masterfiles/pull/1956
The plugins directory has gone unused since it's introduction in 2013. This
change cleans up the plugins directory if it exists and is not empty. If it is
not empty the user is informed and asked to review their policy.
Ticket: CFE-3518
> CFE-3518: Removed unused plugins directory (master)

- deps-packaging/release-monitoring.json
Issue was that old "project" was deleted from release-monitoring.org website.
Reason for it is probably because php 7.1 is EOL according to php.net, so they
migrated from "(current) downloads" to "(unsupported historical) releases" page.
----
#
> Update release-monitoring project used for php7.1

- deps-packaging/release-monitoring.json
It was set to generic "php" before, which tries to download php8 now.
Now it's "php74".
----
#
> Update release-monitoring project for php

- build-remote
- build-scripts/travis
ldap-api repo has been copied to mission-portal/ldap
Ticket: ENT-6448
https://github.com/cfengine/buildscripts/pull/815
https://github.com/cfengine/mission-portal/pull/1323
> ENT-6448 Removed references to ldap-api repo

- build-remote
- build-scripts/travis
ldap-api repo has been copied to mission-portal/ldap
Ticket: ENT-6448
(cherry picked from commit 6a115b634d80f7a7fe969202d5a8c1ff7c3611c8)
Conflicts:
build-remote
build-scripts/travis
merge together
https://github.com/cfengine/mission-portal/pull/1335
https://github.com/cfengine/buildscripts/pull/825
> ENT-6448 Removed references to ldap-api repo (3.12.x)

- build-remote
- build-scripts/travis
ldap-api repo has been copied to mission-portal/ldap
Ticket: ENT-6448
(cherry picked from commit 6a115b634d80f7a7fe969202d5a8c1ff7c3611c8)
Conflicts:
build-remote
build-scripts/travis
merge together
https://github.com/cfengine/mission-portal/pull/1336
https://github.com/cfengine/buildscripts/pull/826
> ENT-6448 Removed references to ldap-api repo (3.15.x)

- build-scripts/travis
custom_promise_binary is not available in travis CI for
mission-portal CI. The test will be run in core CI because
acceptance tests are run with core/travis-scripts/script.sh
instead of this buildscripts script.
Ticket: CFE-3526
> CFE-3526 Skip 13_binary_path.cf test on travis due to missing binary

- build-scripts/bootstrap-tarballs
To speed up './configure' in core which recursively runs
'./configure' in libntech and the two runs can share the cached
values.
> Use config.cache when producing core tarballs

- deps-packaging/release-monitoring.json
NOTE TO SELF: remember to revert this commit on master after 3.18.x branched off!
Reason my to do it - to perform dependency updates on master.
They must follow to 3.18.x branch and be kept on master.
Otherwise, it would look silly to have deps on master with versions lower than
on a stabilisation branch :) And who knows how long will it take for PostgreSQL
guys to release a version 14.
> TEMPORARY switch to PostgreSQL 13.x project in release-monitoring.org

- build-scripts/test-chroot
After reading some Internets, I believe that the way for hostname -f is supposed
to work is this:
* First, get IP of current hostname
* Second, get FQDN of this IP (consulting /etc/hosts, if necessary)
I'm not sure how it works outside of chroot, and why that way stopped working
inside of chroot in Ubuntu 20, but looks like adding this line makes hostname -f work.
(cherry picked from commit c9fbc0b121e7f4dd061e5f44381c641c9b494e0f)
> ENT-6552 ensure hostname -f works inside chroot - 3.18.x

- build-scripts/test-chroot
This partially reverts commit c9fbc0b121e7f4dd061e5f44381c641c9b494e0f.
> ENT-6552 ensure hostname -f fix doesn't break exotics

- build-scripts/test-chroot
(cherry picked from commit af258180a23ef4d12ec07fc25f9b5b74588a101e)
> ENT-6552 ensure hostname -f fix doesn't break exotics - 3.18.x

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
In particular, simple `mkdir` doesn't create the folder(s) with
correct SELinux label, unless the `-Z` option is used.
Ticket: ENT-7898
Changelog: VCS configuration now works on RHEL 8 hubs
> ENT-7898: Make sure files and dirs created in scriptlets have correct SELinux labels

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
In particular, simple `mkdir` doesn't create the folder(s) with
correct SELinux label, unless the `-Z` option is used.
Ticket: ENT-7898
Changelog: VCS configuration now works on RHEL 8 hubs
(cherry picked from commit 5916ff7232c66406ff81ce9ed7a0f7cf9125773e)
> [3.15.x] ENT-7898: Make sure files and dirs created in scriptlets have correct SELinux labels

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
In particular, simple `mkdir` doesn't create the folder(s) with
correct SELinux label, unless the `-Z` option is used.
Ticket: ENT-7898
Changelog: VCS configuration now works on RHEL 8 hubs
(cherry picked from commit 5916ff7232c66406ff81ce9ed7a0f7cf9125773e)
> [3.18.x] ENT-7898: Make sure files and dirs created in scriptlets have correct SELinux labels

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
rpmbuild fails if a listed file is not present at build time. This change makes
sure the file exists in the build root. Also, having the postgresql.log listed
in files will make rpm understand that the CFEngine hub package actually owns
the file, which is a great improvement.
> ENT-7966: Added creation of postgresql.log to nova hub package build

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
rpmbuild fails if a listed file is not present at build time. This change makes
sure the file exists in the build root. Also, having the postgresql.log listed
in files will make rpm understand that the CFEngine hub package actually owns
the file, which is a great improvement.
(cherry picked from commit f2de79ee7be5bfe4c88bd4f810dccac8f2934a73)
> ENT-7966: Added creation of postgresql.log to nova hub package build (3.15)

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
rpmbuild fails if a listed file is not present at build time. This change makes
sure the file exists in the build root. Also, having the postgresql.log listed
in files will make rpm understand that the CFEngine hub package actually owns
the file, which is a great improvement.
(cherry picked from commit f2de79ee7be5bfe4c88bd4f810dccac8f2934a73)
> ENT-7966: Added creation of postgresql.log to nova hub package build (3.18)

- deps-packaging/pkg-get-src
For sourceforge we needed the download URL and resulting filename
to be different. This commit fixes the filename provided to pkg-cache.
Ticket: ENT-7955
(cherry picked from commit a9869e476e7e78a32da5f6ee93a4f1d5d3eee545)
> ENT-7955 Use third arg in distfiles for pkg-cache if provided (3.15)

- deps-packaging/pkg-get-src
For sourceforge we needed the download URL and resulting filename
to be different. This commit fixes the filename provided to pkg-cache.
Ticket: ENT-7955
(cherry picked from commit a9869e476e7e78a32da5f6ee93a4f1d5d3eee545)
> ENT-7955 Use third arg in distfiles for pkg-cache if provided (3.18)

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
This is a fix for umask changes in ENT-7948
Ticket: ENT-8065
merge together
https://github.com/cfengine/mission-portal/pull/1578
https://github.com/cfengine/masterfiles/pull/2168
https://github.com/cfengine/buildscripts/pull/908
> ENT-8065 Gave cfapache group full access to httpd contents

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
This is a fix for umask changes in ENT-7948
Ticket: ENT-8065
(cherry picked from commit 540d5505b44cf8ae219695a6da1ba1d6b10ec411)
> ENT-8065: Gave cfapache group full access to httpd contents (3.18)

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
This is a fix for umask changes in ENT-7948
Ticket: ENT-8065
(cherry picked from commit 540d5505b44cf8ae219695a6da1ba1d6b10ec411)
> ENT-8065: Gave cfapache group full access to httpd contents (3.15)

- packaging/common/cfengine-hub/postinstall.sh
So that it is created as part of the installation process and,
among other things, gets the right SELinux label.
> Create /opt/cfengine/notification_scripts in post-install

- packaging/common/cfengine-hub/postinstall.sh
So that it is created as part of the installation process and,
among other things, gets the right SELinux label.
(cherry picked from commit 480cfc5975b19ad004e6321dd49183a48f7694df)
> ENT-8029: Create /opt/cfengine/notification_scripts in post-install (3.18)

- packaging/common/cfengine-hub/postinstall.sh
So that it is created as part of the installation process and,
among other things, gets the right SELinux label.
(cherry picked from commit 480cfc5975b19ad004e6321dd49183a48f7694df)
> ENT-8029: Create /opt/cfengine/notification_scripts in post-install (3.15)

- packaging/common/cfengine-hub/postinstall.sh
Otherwise it will fail if the directory already exists.
> Add '-p' when creating the /opt/cfengine/notification_scripts dir

- packaging/common/cfengine-hub/postinstall.sh
Otherwise it will fail if the directory already exists.
(cherry picked from commit 0fe4c185989e2f896d44eac9cd695ac59d0ae5fd)
> [3.18.x] Add '-p' when creating the /opt/cfengine/notification_scripts dir

- packaging/common/cfengine-hub/postinstall.sh
Otherwise it will fail if the directory already exists.
(cherry picked from commit 0fe4c185989e2f896d44eac9cd695ac59d0ae5fd)
> [3.15.x] Add '-p' when creating the /opt/cfengine/notification_scripts dir

- packaging/common/cfengine-hub/preinstall.sh
Otherwise, at the end of (successful) upgrade, it will be deleted.
If it contained any user data - that data will be gone.
Ticket: ENT-7944
> Ensure that BACKUP_DIR is empty before processing

- packaging/common/cfengine-hub/preinstall.sh
Location on debian 9 is /bin/ss so prefer to use command -v
to check for existence.
netstat is not available by default on newer debian based
distributions.
Ticket: ENT-8293
(cherry picked from commit b684ff1947893f3564d3be299552fa3e202decc0)
> ENT-8293 Improve check for 'ss' command on newer debian distros (3.18)

- packaging/common/cfengine-hub/preinstall.sh
Location on debian 9 is /bin/ss so prefer to use command -v
to check for existence.
netstat is not available by default on newer debian based
distributions.
Ticket: ENT-8293
> ENT-8293 Improve check for 'ss' command on newer debian distros

- packaging/common/cfengine-hub/preinstall.sh
Location on debian 9 is /bin/ss so prefer to use command -v
to check for existence.
netstat is not available by default on newer debian based
distributions.
Ticket: ENT-8293
(cherry picked from commit b684ff1947893f3564d3be299552fa3e202decc0)
> ENT-8293 Improve check for 'ss' command on newer debian distros (3.15)

- packaging/common/cfengine-hub/preinstall.sh
In case some files are not present do not fail.
Found while testing upgrade on centos6 from 3.15.5 to 3.18.1.
Ticket: ENT-8332
> ENT-8332 Improve preinstall scripts resilience

- packaging/common/cfengine-hub/preinstall.sh
In case some files are not present do not fail.
Found while testing upgrade on centos6 from 3.15.5 to 3.18.1.
Ticket: ENT-8332
(cherry picked from commit 92ab0796622e78030778612839b2aab15436008d)
> ENT-8332 Improve preinstall scripts resilience (3.15)

- packaging/common/cfengine-hub/postinstall.sh
Problem was that a dangling symlink was caused during rpm upgrade
procedure and so was breaking the postinstall scriptlet.
Ticket: ENT-8372
(cherry picked from commit f1b3509cb462ee7d9bd38362df2cbed39f3f6bca)
> ENT-8372 Improved postinstall scriptlet for rpm upgrades (master)

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
Issue was that when /var/cfengine/state/pg/data is a mounted volume, it can't be deleted. First, it makes `rm -rf` fail, and second, it confuses migration logic which checks lack of this directory as a signal to create new postgresql database there (including postgresql.conf file). But when this directory is a mounted volume - `rm -rf` can delete everything inside it, except the directory itself. Empty directory is not a valid postgresql database, what confuses rest of postinstall script.
Note that we don't want to use plain is_upgrade here, because the generate_new_postgres_conf must be executed in two cases:
* on a fresh install
* when a major upgrade of PostgreSQL requires DB migration - happens only during minor CFEngine upgrade (3.15 -> 3.18)
and is_upgrade is, well, _any_ CFEngine …
> Check for existence of pg/data/postgresql.conf file, instead of data dir

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/buildscripts/pull/958
- https://github.com/cfengine/masterfiles/pull/2275
CFEngine Enterprise does not currently use webdav by default, so we do not need
to load these modules. They are still present in the build so users can still
leverage them if desired.
Ticket: ENT-8495
Changelog: CFEngine Enterprise Hub Apache no longer loads webdav modules by default
> ENT-8495: Stopped loading webdav apache modules by default

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2276
- https://github.com/cfengine/buildscripts/pull/959
CFEngine Enterprise does not currently use webdav by default, so we do not need
to load these modules. They are still present in the build so users can still
leverage them if desired.
Ticket: ENT-8495
Changelog: CFEngine Enterprise Hub Apache no longer loads webdav modules by default
(cherry picked from commit d5d994e86fddcc567832d444749ac08f64a6b1b1)
> ENT-8495: Stopped loading webdav apache modules by default (3.18)

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2277
- https://github.com/cfengine/buildscripts/pull/960
CFEngine Enterprise does not currently use webdav by default, so we do not need
to load these modules. They are still present in the build so users can still
leverage them if desired.
Ticket: ENT-8495
Changelog: CFEngine Enterprise Hub Apache no longer loads webdav modules by default
(cherry picked from commit d5d994e86fddcc567832d444749ac08f64a6b1b1)
> ENT-8495: Stopped loading webdav apache modules by default (3.15)

- deps-packaging/apache/httpd.conf
Merge together: 
- https://github.com/cfengine/masterfiles/pull/2285
Since we do not use the features provided by this module we don't need to load it
by default.
Ticket: ENT-8504
> ENT-8504: Stopped loading mod_info

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2286
Since we do not use the features provided by this module we don't need to load it
by default.
Ticket: ENT-8504
(cherry picked from commit 7561c6c184c1c81549d4e187056587f335bc456f)
> ENT-8504: Stopped loading mod_info by default (3.18)

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2284
Since we don't make active use of this module, we don't need to load it by default.
Ticket: ENT-8506
> ENT-8506: Stopped loading mod_status by default

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2287
Since we do not use the features provided by this module we don't need to load it
by default.
Ticket: ENT-8504
(cherry picked from commit 7561c6c184c1c81549d4e187056587f335bc456f)
> ENT-8504: Stopped loading mod_info by default (3.15)

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2291
Since we don't make active use of this module, we don't need to load it by default.
Ticket: ENT-8506
(cherry picked from commit fa718ee1f9b8daf0c1be37ed9c2ec20a8b419343)
> ENT-8506: Stopped loading mod_status by default (3.18)

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2292
Since we don't make active use of this module, we don't need to load it by default.
Ticket: ENT-8506
(cherry picked from commit fa718ee1f9b8daf0c1be37ed9c2ec20a8b419343)
> ENT-8506: Stopped loading mod_status by default (3.15)

- deps-packaging/apache/httpd.conf
We do not use the features provided by this module so we should not load it by
default.
Ticket: ENT-8499
> ENT-8499: Stopped loading Apache mod_spelling by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
We do not use the features provided by this module so we should not load it by
default.
Ticket: ENT-8499
(cherry picked from commit d7ae6384014be5d10a574cffe4fcb2bcedb2bb76)
> ENT-8499: Stopped loading Apache mod_spelling by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
We do not use the features provided by this module so we should not load it by
default.
Ticket: ENT-8499
(cherry picked from commit d7ae6384014be5d10a574cffe4fcb2bcedb2bb76)
> ENT-8499: Stopped loading Apache mod_spelling by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
We do not use the functionality provided by this module, so we should  not load
it by default.
Ticket: ENT-8497
> ENT-8497: Stopped loading Apache mod_version by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
We do not use the functionality provided by this module, so we should  not load
it by default.
Ticket: ENT-8497
(cherry picked from commit 0ca6df74c6c5a967556fe002dd23af12bb6a69a6)
> ENT-8497: Stopped loading Apache mod_version by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
We do not use the functionality provided by this module, so we should  not load
it by default.
Ticket: ENT-8497
(cherry picked from commit 0ca6df74c6c5a967556fe002dd23af12bb6a69a6)
> ENT-8497: Stopped loading Apache mod_version by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8514: Stopped loading Apache mod_autoindex by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8514
(cherry picked from commit 2a35b284118c85f8e1a5af8bef07b679dd0e33c2)
> ENT-8514: Stopped loading Apache mod_autoindex by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8514
(cherry picked from commit 2a35b284118c85f8e1a5af8bef07b679dd0e33c2)
> ENT-8514: Stopped loading Apache mod_autoindex by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8522: Stopped loading Apache mod_env by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8522
(cherry picked from commit 8fe4a3ad49456e70248e317dd2b804745f965ae7)
> ENT-8522: Stopped loading Apache mod_env by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8522
(cherry picked from commit 8fe4a3ad49456e70248e317dd2b804745f965ae7)
> ENT-8522: Stopped loading Apache mod_env by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2294
Since we do not use the functionality provided by this module, we should not
load it by default.
Ticket: ENT-8498
(cherry picked from commit dd6610c4dd9ef27395670f187f179869ea22f885)
> ENT-8498: Stopped loading Apache substitute module by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
- https://github.com/cfengine/masterfiles/pull/2295
Since we do not use the functionality provided by this module, we should not
load it by default.
Ticket: ENT-8498
(cherry picked from commit dd6610c4dd9ef27395670f187f179869ea22f885)
> ENT-8498: Stopped loading Apache substitute module by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8503: Stopped loading Apache mod_actions by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8505: Stopped loading Apache mod_asis by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8505
(cherry picked from commit 943005a7458fecb059dd64bbf4a55fdcf6896a27)
> ENT-8505: Stopped loading Apache mod_asis by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8505
(cherry picked from commit 943005a7458fecb059dd64bbf4a55fdcf6896a27)
> ENT-8505: Stopped loading Apache mod_asis by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8507: Stopped loading Apache mod_include by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8507
(cherry picked from commit d2a6b30a1a936e48c7b94d579786d01b5ede30cd)
> ENT-8507: Stopped loading Apache mod_include by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8507
(cherry picked from commit d2a6b30a1a936e48c7b94d579786d01b5ede30cd)
> ENT-8507: Stopped loading Apache mod_include by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8509: Stopped loading Apache mod_ldap by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8509
(cherry picked from commit cd37b0f99bcf90b96d64485f73bc1c7d06de6d08)
> ENT-8509: Stopped loading Apache mod_ldap by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8509
(cherry picked from commit cd37b0f99bcf90b96d64485f73bc1c7d06de6d08)
> ENT-8509: Stopped loading Apache mod_ldap by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8511: Stopped loading Apache mod_negotiation by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8511
(cherry picked from commit 202c5e450e69ac0332f3a4ddf849821e2c224897)
> ENT-8511: Stopped loading Apache mod_negotiation by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8511
(cherry picked from commit 202c5e450e69ac0332f3a4ddf849821e2c224897)
> ENT-8511: Stopped loading Apache mod_negotiation by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8512
(cherry picked from commit f6ca48f6f239c93235f6d9520ab1c57bbbb76ad4)
> ENT-8512: Stopped loading Apache mod_authnz_ldap by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8512: Stopped loading Apache mod_authnz_ldap by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8513: Stopped loading Apache mod_vhost_alias by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8513: Stopped loading Apache mod_vhost_alias by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8513: Stopped loading Apache mod_vhost_alias by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8517: Stopped loading Apache mod_mime_magic by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8517
(cherry picked from commit 9f0f380c1ac3a7c2651d942e0a1cb344a74e400a)
> ENT-8517: Stopped loading Apache mod_mime_magic by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8517
(cherry picked from commit 9f0f380c1ac3a7c2651d942e0a1cb344a74e400a)
> ENT-8517: Stopped loading Apache mod_mime_magic by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8519: Stopped loading Apache mod_unique_id by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8519
(cherry picked from commit fcdf325c2d430a4285f47ff3e65bdf3d57421f8e)
> ENT-8519: Stopped loading Apache mod_unique_id by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8519
(cherry picked from commit fcdf325c2d430a4285f47ff3e65bdf3d57421f8e)
> ENT-8519: Stopped loading Apache mod_unique_id by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8521: Stopped loading Apache mod_usertrack by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8521
(cherry picked from commit 817c8ae2da066353181566bddc8fa3bb122b8a00)
> ENT-8521: Stopped loading Apache mod_usertrack by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8521
(cherry picked from commit 817c8ae2da066353181566bddc8fa3bb122b8a00)
> ENT-8521: Stopped loading Apache mod_usertrack by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8501: Stopped loading Apache mod_log_forensic by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8501
(cherry picked from commit 51d2fd409614ca1741d09d8e22113fa54b964b21)
> ENT-8501: Stopped loading Apache mod_log_forensic by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
default.
Ticket: ENT-8501
(cherry picked from commit 51d2fd409614ca1741d09d8e22113fa54b964b21)
> ENT-8501: Stopped loading Apache mod_log_forensic by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8526: Stopped loading Apache mod_dumpio by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8526: Stopped loading Apache mod_dumpio by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8526: Stopped loading Apache mod_dumpio by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8525: Stopped loading Apache mod_reqtimeout by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8525: Stopped loading Apache mod_reqtimeout by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8525: Stopped loading Apache mod_reqtimeout by default on Enterprise Hubs (3.15)

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
Otherwise it cannot be executed.
> Make sure /var/cfengine/bin/cfbs is executable in RPMs

- deps-packaging/apache/httpd.conf
We do not use the features provided by these modules, so we should not load them by default.
> ENT-8524: Stopped loading Apache mod_filter and mod_ext_filter by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
We do not use the features provided by these modules, so we should not load them by default.
> ENT-8524: Stopped loading Apache mod_filter and mod_ext_filter by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
We do not use the features provided by these modules, so we should not load them by default.
> ENT-8524: Stopped loading Apache mod_filter and mod_ext_filter by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8523: Stopped loading Apache mod_deflate by default on Enterprise Hubs

- packaging/common/script-templates/script-common.sh
It's kind of nice to know why what's happening. Reading the log prior to this
change, you see that something is copied and deleted and copied and maybe
deleted again for why? This simply prints out some messages in the event of
failure so that it's a bit easier to read the logs.
> Improved enterprise hub package upgrade logging

- packaging/common/script-templates/script-common.sh
It's kind of nice to know why what's happening. Reading the log prior to this
change, you see that something is copied and deleted and copied and maybe
deleted again for why? This simply prints out some messages in the event of
failure so that it's a bit easier to read the logs.
(cherry picked from commit eb13ca5b37e5ffc92ac695e6c92dbd0f6dc59571)
> Fixed behavioral comment, improved logging of issues encountered (3.18)

- packaging/common/script-templates/script-common.sh
It's kind of nice to know why what's happening. Reading the log prior to this
change, you see that something is copied and deleted and copied and maybe
deleted again for why? This simply prints out some messages in the event of
failure so that it's a bit easier to read the logs.
(cherry picked from commit eb13ca5b37e5ffc92ac695e6c92dbd0f6dc59571)
> Fixed behavioral comment, improved logging of issues encountered (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8523: Stopped loading Apache mod_deflate by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
This change is intended to better document and understand our use of Apache
modules in the default configuration.
> ENT-8554: Added in-line reasoning for use of Apache modules (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8598: Stopped loading Apache mod_authn_file by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8599: Stopped loading Apache mod_authn_dbm by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8599: Stopped loading Apache mod_authn_dbm by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
Ticket: ENT-8599
(cherry picked from commit 27fbc75f884b459771fc4171b2e0e8da238a6ec2)
> ENT-8599: Stopped loading Apache mod_authn_dbm by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8604: Stopped loading Apache mod_authz_user by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8604: Stopped loading Apache mod_authz_user by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8604: Stopped loading Apache mod_authz_user by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8600: Stopped loading Apache mod_authn_anon by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8600: Stopped loading Apache mod_authn_anon by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8600: Stopped loading Apache mod_authn_anon by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8610: Stopped loading Apache mod_expires by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8610: Stopped loading Apache mod_expires by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8601: Stopped loading Apache mod_authn_dbd by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8608: Stopped loading Apache mod_auth_digest by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8601: Stopped loading Apache mod_authn_dbd by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8603: Stopped loading Apache mod_authz_groupfile by default on Enterprise Hubs

- deps-packaging/apache/httpd.conf
> ENT-8601: Stopped loading Apache mod_authn_dbd by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8608: Stopped loading Apache mod_auth_digest by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8608: Stopped loading Apache mod_auth_digest by default on Enterprise Hubs (3.15)

- deps-packaging/apache/httpd.conf
> ENT-8603: Stopped loading Apache mod_authz_groupfile by default on Enterprise Hubs (3.18)

- deps-packaging/apache/httpd.conf
> ENT-8603: Stopped loading Apache mod_authz_groupfile by default on Enterprise Hubs (3.15)

- build-scripts/exotics.txt
They are fairly fast, cheaper than most instances in AWS,
and would be cool to provide them as nightlies to folks.
Ticket: none
> Move ubuntu 22 arm builds out of exotics

- packaging/common/cfengine-hub/preinstall.sh
Ticket: ENT-8837
(cherry picked from commit 44ead9475a66e2dcd37f264d5d78dcb67a1b91b9)
> ENT-8837 Ensure that no valid hostname produces error during hub package install (3.15)

- deps-packaging/apache/apachectl.patch
Copy of the CFEngine-vendored apachectl file exists in masterfiles repo.
That repo doesn't allow trailing whitespace. And we want two copies of
this file to be identical. Hence, we update this patch to strip trailing
whitespace.
> Update apachectl.patch to strip trailing whitespace - master

- deps-packaging/apache/apachectl.patch
Copy of the CFEngine-vendored apachectl file exists in masterfiles repo.
That repo doesn't allow trailing whitespace. And we want two copies of
this file to be identical. Hence, we update this patch to strip trailing
whitespace.
> Update apachectl.patch to strip trailing whitespace - 3.18.x

- deps-packaging/apache/apachectl.patch
Copy of the CFEngine-vendored apachectl file exists in masterfiles repo.
That repo doesn't allow trailing whitespace. And we want two copies of
this file to be identical. Hence, we update this patch to strip trailing
whitespace.
> Update apachectl.patch to strip trailing whitespace - 3.15.x

- build-scripts/travis
Travis has a limit of 4Mb log size.
This suppresses some output to make our builds fit into the limit.
> Quieter travis log

- build-scripts/configure
For some reason, on SUSE 15, cfengine-enterprise.so ends up in
/var/cfengine/lib64.
> Make sure our libraries are installed to /var/cfengine/lib not lib64

- build-scripts/configure
For some reason, on SUSE 15, cfengine-enterprise.so ends up in
/var/cfengine/lib64.
(cherry picked from commit a8789ded1b177e292d9c27fdad3fbf1e5a4c7c32)
> ENT-9033: Make sure our libraries are installed to /var/cfengine/lib not lib64 (3.18)

- build-scripts/configure
For some reason, on SUSE 15, cfengine-enterprise.so ends up in
/var/cfengine/lib64.
(cherry picked from commit a8789ded1b177e292d9c27fdad3fbf1e5a4c7c32)
> ENT-9033: Make sure our libraries are installed to /var/cfengine/lib not lib64 (3.15)

- build-scripts/labels.txt
Possibly replace ubuntu 22 with debian 11 if the debian
packages work on ubuntu 22.
Ticket: ENT-8978
> ENT-8978: Add debian 11 aarch64 labels

- deps-packaging/libgcc/solaris/build
Note that this assumes that we build only 64-bit binaries on sparc, and 32-bit binaries on other platforms. As of writing, this is correct ("other platforms" being only 32-bit x86 Intel).
Ticket: ENT-9013
Issue was that recently we switched to building 64-bit binaries on sparc (apparently they can run both 32 and 64-bit), but we still were packaging 32-bit library, and thus all our binaries were crashing on start.
> Take 64-bit library on sparc and 32-bit library elsewhere

- packaging/cfengine-nova/cfengine-nova.bff.sh
Ticket: ENT-8941
(cherry picked from commit c252cc99de0a0ca6d6bead5aac4c6362d58cbf87)
> Remove extra 'cfengine' prefix from bff filename - 3.18.x

- deps-packaging/lmdb/0011-assert-on-mdb-mutex-failed.patch
To debug issues related to the following log message:
error: Could not open database txn /var/cfengine/state/cf_lock.lmdb: Invalid argument
Ticket: CFE-3807
(cherry picked from commit 43434600f675b352b1fcbd41ef3054df3270c397)
> CFE-3807: Added assert on EINVAL in mdb_mutex_failed() (3.18)

- deps-packaging/lmdb/0011-assert-on-mdb-mutex-failed.patch
To debug issues related to the following log message:
error: Could not open database txn /var/cfengine/state/cf_lock.lmdb: Invalid argument
Ticket: CFE-3807
related: 
https://github.com/cfengine/core/pull/5073
https://github.com/cfengine/buildscripts/pull/1131
https://github.com/cfengine/system-testing/pull/457
> CFE-3807: Added assert on EINVAL in mdb_mutex_failed()

- build-scripts/labels.txt
> ENT-9595: add debian 11 and ubuntu 22 platforms, aarch64 and x86_64

- build-scripts/exotics.txt
By removing them from exotics this adds them to the list to use in nightlies/testing-pr job.
Ticket: ENT-9595
> ENT-9595: Add Ubuntu 22 aarch64/arm agent and hub labels

- build-scripts/configure
- build-scripts/labels.txt
- deps-packaging/cache-sftp
- packaging/common/cfengine-hub/preremove.sh
- packaging/common/cfengine-non-hub/postinstall.sh
- packaging/common/cfengine-non-hub/preremove.sh
Ticket: ENT-8824
Summary of pending issues in CI:
https://github.com/cfengine/buildscripts/pull/1137
https://github.com/cfengine/system-testing/pull/462
https://github.com/cfengine/masterfiles/pull/2529
https://github.com/cfengine/core/pull/5111
> ENT-8824: add support for redhat 9 agent package

- deps-packaging/apache/httpd.conf
-  https://github.com/cfengine/masterfiles/pull/2545
When this was removed from buildscripts it also needed to be removed from the
template in masterfiles. We spent some time hunting down the issue before we
realized this was a change we made, not an upstream difference. Rather than
removing it from the config in masterfiles completely we stub it out with an
explanation.
Ticket: ENT-9600
> ENT-9600: Added note about why SSLCompression is not explicitly off

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
That's what our libraries are linked to:
[vagrant@centos9s ~]$ ldd /var/cfengine/lib/libpromises.so.3.0.6 |grep -P '(ssl|crypto)'
libssl.so.3 => /lib64/libssl.so.3 (0x00007fa73b37c000)
libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007fa73ae00000)
and without this change, we pull in the 'compat-openssl11' package as a dependency which is unnecessary and potentially a problem for security scans, etc.
Ticket: ENT-8824
> Require OpenSSL 3 on RHEL 9 and newer

- deps-packaging/apache/httpd.conf
Otherwise, it's not getting replaced by the one rendered from masterfiles, and cf-agent restarts apache every five minutes.
Ticket: ENT-9696
> Add a warning to httpd.conf

- build-scripts/labels.txt
- deps-packaging/pkg-build-rpm
Ticket: ENT-9605
together:
https://github.com/cfengine/nova/pull/1964
https://github.com/cfengine/buildscripts/pull/1173
> ENT-9605: Added rhel-9 hub package label

- packaging/common/cfengine-hub/postinstall.sh
Ticket: ENT-9665
https://github.com/cfengine/buildscripts/pull/1179
https://github.com/cfengine/masterfiles/pull/2562
> ENT-9665: Added correct permissions for build directory in Mission Portal

- packaging/common/cfengine-hub/postinstall.sh
Needs to be owned root:cfapache with execute from php up so that httpd can access.
Ticket: ENT-9711
> ENT-9711: Added postinstall runalerts-temp directory management

- deps-packaging/apache/httpd.conf
Otherwise, it's not getting replaced by the one rendered from masterfiles, and cf-agent restarts apache every five minutes.
Ticket: ENT-9696
(cherry picked from commit f50a67f00f0e207cf9e795ca4865eeeeaeccaa81)
> Add a warning to httpd.conf - 3.18.x

- packaging/common/cfengine-hub/postinstall.sh
Needs to be owned root:cfapache with execute from php up so that httpd can access.
Ticket: ENT-9711
(cherry picked from commit 421193c3d8bb6673295bd1152b531c18e799f72e)
together:
https://github.com/cfengine/buildscripts/pull/1188
https://github.com/cfengine/masterfiles/pull/2569
https://github.com/cfengine/core/pull/5149
> ENT-9711: Added postinstall runalerts-temp directory management (3.18)

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-community/debian/control
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova-hub/debian/control
- packaging/cfengine-nova/cfengine-nova.spec.in
- packaging/cfengine-nova/debian/control
- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
Investigation shows that the only place where it's _required_ was when compressing man pages. But `man` can also work with uncompressed pages.
Other places which use gzip are Federated Reporting, watchdog script, and self-upgrade on Solaris, - all these parts are not "essential".
So it was decided to downgrade gzip requirement to "Recommends".
Also worth noting that it's essential part of system on many distibutions, and it's pretty hard to find a platform without gzip.
Ticket: ENT-9113
> Make gzip a weak dependency

- .github/dependabot.yml
We don't use this convention in CFEngine projects. See: https://github.com/cfengine/core/blob/master/CONTRIBUTING.md
> dependabot: Removed chore prefix for commit messages

- packaging/cfengine-nova/cfengine-nova.wxs
otherwise, cf-secret.exe was packaged into *.msi, but not installed on a target machine
Ticket: ENT-10405
> Added cf-secret ComponentRef

- .github/workflows/build-using-buildscripts.yml
We control the code, so no need to be "careful" here.
Ticket: ENT-10442
> ENT-10442: Switch together-javascript-action to main to avoid dependency update work

- .github/workflows/build-using-buildscripts.yml
- .gitignore
- README.md
- build-scripts/clean-dependencies
- ci/Dockerfile-cfengine-build-package
- ci/README
- ci/build.sh
- ci/clean.sh
- ci/docker.sh
- ci/setup-projects.sh
- ci/setup.sh
- ci/shell.sh
- deps-packaging/libattr/source
https://github.com/cfengine/mission-portal/pull/1996
> ENT-9167: Added ci docker scripts for manual and github actions use

- build-scripts/exotics.txt
Ticket: INF-3402
(cherry picked from commit 177429615d76eb75908f86027fa29352834a01a3)
> INF-3402: Removed aix71 exotic while build host is being built (3.21)

- build-scripts/exotics.txt
Ticket: INF-3402
(cherry picked from commit 177429615d76eb75908f86027fa29352834a01a3)
> INF-3402: Removed aix71 exotic while build host is being built (3.18)

- build-scripts/labels.txt
(cherry picked from commit d5b8105a95e166d020d504834d9fa5234b5bc86e)
Conflicts:
build-scripts/labels.txt
> INF-3402: Removed aix71 label while build host is being built (3.18)

- build-scripts/labels.txt
(cherry picked from commit d5b8105a95e166d020d504834d9fa5234b5bc86e)
> INF-3402: Removed aix71 label while build host is being built (3.21)

- build-scripts/exotics.txt
- build-scripts/functions
- build-scripts/labels.txt
> INF-3402: Added aix71 label back now that build host is prepared

- .github/workflows/deployment-tests.yml
- ci/package-sha.sh
with https://github.com/cfengine/nova/pull/2091
> ENT-9170: Made deployment-tests workflow sharable by other projects

- ci/build.sh
- ci/clean-build-package.sh
- ci/docker-build-package.sh
- deps-packaging/zlib/source
Keeping the old release requires using the https://zlib.net/fossils/ base URL
Ticket: ENT-9517
> ENT-9517: Modified zlib URL to adjust for new release

- deps-packaging/zlib/source
Probably package cache was avoiding this issue somehow.
Ticket: ENT-9517
> ENT-9517: Fixed zlib 1.2.12 details

- .github/workflows/deployment-tests.yml
- ci/package-sha.sh
Ticket: ENT-9170
(cherry picked from commit 2c9591334bf1f7f9b5b6842ce9452dfa811a8284)
with https://github.com/cfengine/nova/pull/2096
> ENT-9170: Made deployment-tests workflow sharable by other projects (3.21)

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
It's not needed anymore, and takes 30 seconds on each build
Ticket: ENT-10420
(cherry picked from commit fe7bc33f81cb357fe38bc0260b769092b004bcd7)
> ENT-10420 Remove s/cfapi_log/syslog/ replacement - 3.21.x

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
It's not needed anymore, and takes 30 seconds on each build
Ticket: ENT-10420
(cherry picked from commit fe7bc33f81cb357fe38bc0260b769092b004bcd7)
> ENT-10420 Remove s/cfapi_log/syslog/ replacement - 3.18.x

- packaging/cfengine-nova/cfengine-nova.wxs
otherwise, cf-secret.exe was packaged into *.msi, but not installed on a target machine
Ticket: ENT-10405
(cherry picked from commit 1042d0bfce99ba294ac2e3c01b396514184b606c)
Merge together: https://github.com/cfengine/core/pull/5325
> Added cf-secret ComponentRef - 3.21.x

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/script-templates/script-common.sh
The pg_ctl stop/start commands don't ensure that the server state is as reqeusted
at the moment that the command returns. Added up to 5 seconds of wait time to
ensure the state is as we want.
Also added some tails of expected logs when failures occur. Either /var/log/postgresql.log
or the specific pg_upgrade logs which may be created and mentioned in the output of that command
failing.
> ENT-10647: Added safety for hub upgrade in packaging scriptlets

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/script-templates/script-common.sh
The pg_ctl stop/start commands don't ensure that the server state is as reqeusted
at the moment that the command returns. Added up to 5 seconds of wait time to
ensure the state is as we want.
Also added some tails of expected logs when failures occur. Either /var/log/postgresql.log
or the specific pg_upgrade logs which may be created and mentioned in the output of that command
failing.
(cherry picked from commit a7e6fa707772a9a8e9ca4f4ca307fb4a9a7a2ef2)
> ENT-10647: Added better handling of postgresql server state during hub package install (3.18)

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/script-templates/script-common.sh
The pg_ctl stop/start commands don't ensure that the server state is as reqeusted
at the moment that the command returns. Added up to 5 seconds of wait time to
ensure the state is as we want.
Also added some tails of expected logs when failures occur. Either /var/log/postgresql.log
or the specific pg_upgrade logs which may be created and mentioned in the output of that command
failing.
(cherry picked from commit a7e6fa707772a9a8e9ca4f4ca307fb4a9a7a2ef2)
> ENT-16047: Added better handling of postgresql server state during hub package install (3.21)

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/script-templates/script-common.sh
One typo fix. This was causing failure in ALL upgrades. Ouch.
Changed wait time for server stop/start from 5 seconds to 60.
Added cf_console to pg_upgrade failure tailing so it is visible in console.
Changed condition to test for stopped/started to something that works with tighter restrictions.
Using a select as root was failing due to lack of an account in postgresql at the moment we
were checking: bare database without any further manipulation by setup scripts.
> ENT-10647: Fixed and improved postgresql server state handling in package scriptlets

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
Try to run restorecon with the least number of processes/services running that might
make changes to /var/cfengine and /opt/cfengine
restorecon seems to gather a list of files up-front and then process which can take more
than a few seconds.
When services such as database or cf-execd/cf-agent/etc are running files can change
causing restorecon to error out when files are removed.
The files being removed doesn't create a risk of bad SELinux labels since they are gone.
Ticket: ENT-10429
> ENT-10429: Guarded against race condition in install scriptlets with restorecon

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/script-templates/script-common.sh
One typo fix. This was causing failure in ALL upgrades. Ouch.
Changed wait time for server stop/start from 5 seconds to 60.
Added cf_console to pg_upgrade failure tailing so it is visible in console.
Changed condition to test for stopped/started to something that works with tighter restrictions.
Using a select as root was failing due to lack of an account in postgresql at the moment we
were checking: bare database without any further manipulation by setup scripts.
(cherry picked from commit 83c91b5796be5f910b8b710df86391f2da533e61)
> ENT-10647: Fixed and improved postgresql server state handling in package scriptlets (3.21)

- ci/package-sha.sh
- packaging/common/cfengine-hub/postinstall.sh
> ENT-10710: Fixed issue with using pg_upgrade on ubuntu-16 hub installer upgrade

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
Try to run restorecon with the least number of processes/services running that might
make changes to /var/cfengine and /opt/cfengine
restorecon seems to gather a list of files up-front and then process which can take more
than a few seconds.
When services such as database or cf-execd/cf-agent/etc are running files can change
causing restorecon to error out when files are removed.
The files being removed doesn't create a risk of bad SELinux labels since they are gone.
Ticket: ENT-10429
(cherry picked from commit ee768186c07e45b2d9e9917e00afda79764597b1)
> ENT-10429: Guarded against race condition in install scriptlets with restorecon (3.18)

- packaging/common/script-templates/script-common.sh
It was found that an LC_CTYPE=UTF-8 from iTerm2 on OSX was breaking the hub package install.
Also use su - (--login) option to preserve this LC_ALL setting
PostgreSQL docs suggest using 'C' locale unless otherwise needed
https://www.postgresql.org/docs/current/locale.html
> The drawback of using locales other than C or POSIX in PostgreSQL is its performance impact. It slows character handling and prevents ordinary indexes from being used by LIKE. For this reason use locales only if you actually need them.
Ticket: ENT-10739
together
https://github.com/cfengine/system-testing/pull/508 (rhel-8 hub deployment test use 2G instead of 1G RAM)
> ENT-10739: Force default 'C' locale for package scriptlets

- packaging/common/cfengine-hub/postinstall.sh
The failure warning about postgres cannot execute snags us in our tests but
is fine because we proceed to upgrade in a different way during upgrade.
Ticket: ENT-10710
> ENT-10710: Silence pg_upgrade check warning for debian-9

- packaging/common/cfengine-hub/postinstall.sh
The failure warning about postgres cannot execute snags us in our tests but
is fine because we proceed to upgrade in a different way during upgrade.
Ticket: ENT-10710
(cherry picked from commit 3c218be5a303658ce646d318d51fc171855f1189)
> ENT-10710: Silence pg_upgrade check warning for debian-9 (3.18)

- packaging/common/cfengine-hub/postinstall.sh
The failure warning about postgres cannot execute snags us in our tests but
is fine because we proceed to upgrade in a different way during upgrade.
Ticket: ENT-10710
(cherry picked from commit 3c218be5a303658ce646d318d51fc171855f1189)
> ENT-10710: Silence pg_upgrade check warning for debian-9 (3.21)

- packaging/common/script-templates/script-common.sh
It was found that an LC_CTYPE=UTF-8 from iTerm2 on OSX was breaking the hub package install.
PostgreSQL docs suggest using 'C' locale unless otherwise needed
https://www.postgresql.org/docs/current/locale.html
> The drawback of using locales other than C or POSIX in PostgreSQL is its performance impact. It slows character handling and prevents ordinary indexes from being used by LIKE. For this reason use locales only if you actually need them.
Ticket: ENT-10739
(cherry picked from commit 2db105c6a89c6e2d400bdd1d45f9210f1337ef3c)
> ENT-10739: Improved locale env vars safety during installation for postgresql (3.21)

- packaging/common/script-templates/script-common.sh
It was found that an LC_CTYPE=UTF-8 from iTerm2 on OSX was breaking the hub package install.
PostgreSQL docs suggest using 'C' locale unless otherwise needed
https://www.postgresql.org/docs/current/locale.html
> The drawback of using locales other than C or POSIX in PostgreSQL is its performance impact. It slows character handling and prevents ordinary indexes from being used by LIKE. For this reason use locales only if you actually need them.
Ticket: ENT-10739
(cherry picked from commit 2db105c6a89c6e2d400bdd1d45f9210f1337ef3c)
> ENT-10739: Improved locale env vars safety during installation for postgresql (3.18)

- build-scripts/package-msi
Just to be sure if sftp cache is compromised, fail if checksums don't match.
Ticket: ENT-10801
> ENT-10801: Added checksums for wix tools coming from sftp cache

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
The `cfengine3.service` uses `Wants` to start all the other available CFEngine services. `systemctl enable` on one of the individual services causes them to be started in their respective `.target` (e.g. `multi-user.target`) and thus `systemctl disable cfengine3` is not enough to stop them from being started on boot.
Being able to enable individual services is useful, but it shouldn't be done by default.
https://github.com/cfengine/core/pull/5362
https://github.com/cfengine/buildscripts/pull/1332
> Do not `systemctl enable` individual services

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
The `cfengine3.service` uses `Wants` to start all the other available CFEngine services. `systemctl enable` on one of the individual services causes them to be started in their respective `.target` (e.g. `multi-user.target`) and thus `systemctl disable cfengine3` is not enough to stop them from being started on boot.
Being able to enable individual services is useful, but it shouldn't be done by default.
(cherry picked from commit f53a8f12a66ed19b7a73fab582b2f354357e8023)
> [3.21.x] Do not `systemctl enable` individual services

- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
The `cfengine3.service` uses `Wants` to start all the other available CFEngine services. `systemctl enable` on one of the individual services causes them to be started in their respective `.target` (e.g. `multi-user.target`) and thus `systemctl disable cfengine3` is not enough to stop them from being started on boot.
Being able to enable individual services is useful, but it shouldn't be done by default.
(cherry picked from commit f53a8f12a66ed19b7a73fab582b2f354357e8023)
> [3.18.x] Do not `systemctl enable` individual services

- build-scripts/labels.txt
Merge together with:
- https://github.com/mendersoftware/infra/pull/382
- https://github.com/cfengine/system-testing/pull/506
- https://github.com/cfengine/core/pull/5363
> ENT-10347: Added Debian 12 label to buildscripts

- deps-packaging/autoconf/cfbuild-autoconf.spec
- deps-packaging/autoconf/distfiles
- deps-packaging/automake/cfbuild-automake.spec
- deps-packaging/automake/distfiles
- deps-packaging/libcurl/cfbuild-libcurl.spec
- deps-packaging/libcurl/distfiles
- deps-packaging/libgcc/cfbuild-libgcc.spec
- deps-packaging/libtool/cfbuild-libtool.spec
- deps-packaging/libtool/distfiles
Added missing dependency updates for 3.18.x after https://github.com/cfengine/buildscripts/pull/1351
* Updated libcurl-hub from 8.2.1 to 8.5.0
* Upgraded autoconf from 2.69 to 2.71
* Updated automake from 1.10.1 to 1.10.3
* Updated libgcc from 4.2.0 to 4.2.4
* Updated libtool from 1.5.24 to 1.5.26
> ENT-10966: Added missing dependency updates for 3.18.x

- build-scripts/labels.txt
* https://github.com/cfengine/core/pull/5411
> ENT-10997: Added Debian 12 labels to buildscripts (3.18.x)

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
See also: https://github.com/cfengine/masterfiles/pull/2797
> ENT-11094: Improved rpm verification for hub package

- packaging/common/cfengine-hub/postinstall.sh
> ENT-11191: Silence `pg_upgrade` check warning for Debian 12

- packaging/common/cfengine-hub/postinstall.sh
Backported from https://github.com/cfengine/buildscripts/pull/1364
> ENT-11191: Silence `pg_upgrade` check warning for Debian 12 (3.21.x)

- ci/cfengine-build-host-setup.cf
> ENT-11166: All redhat build hosts should not have libtool-ltdl

- ci/cfengine-build-host-setup.cf
> ENT-11166: Remove ShellCheck from centos-7, it is too old to work with our shellcheck annotations.

- build-scripts/functions
See if another package manager process is locking the package manager database, like /var/lib/dpkg/lock and such
> ENT-11166: Modified retry_wrapper to get more info about package manager retry reasons

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova-hub/debian/rules
- packaging/cfengine-nova/cfengine-nova.spec.in
- packaging/cfengine-nova/debian/cfengine-nova.install
For hubs we already package /var/cfengine/lib/python, we should
also do it in non-hub packages.
Ticket: CFE-4281
https://github.com/cfengine/core/pull/5438
https://github.com/cfengine/buildscripts/pull/1367
> Package Python bindings for our libraries

- build-scripts/functions
See if another package manager process is locking the package manager database, like /var/lib/dpkg/lock and such
(cherry picked from commit 0a2fd9947571eeca891ca8c6afa4e7de371d338e)
> Modified retry_wrapper to get more info about package manager retry reasons (3.21)

- build-scripts/functions
See if another package manager process is locking the package manager database, like /var/lib/dpkg/lock and such
(cherry picked from commit 0a2fd9947571eeca891ca8c6afa4e7de371d338e)
> Modified retry_wrapper to get more info about package manager retry reasons (3.18)

- ci/cfengine-build-host-setup.cf
> ENT-11166: Removed not present ShellCheck package from rhel-9 and rhel-9 build host configs

- ci/cfengine-build-host-setup.cf
> ENT-11166: Fix typo in previous commit related to ci/cfengine-build-host-setup.cf

- ci/cfengine-build-host-setup.cf
- Fixed path to dnf.conf in ci/cfengine-build-host-setup.cf policy
> ENT-11166: Fixed path to dnf.conf in ci/cfengine-build-host-setup.cf policy

- packaging/common/cfengine-hub/postinstall.sh
Just like we do with many other executables we ship in /var/cfengine/bin.
Ticket: ENT-10936
Changelog: /usr/local/sbin/cfbs now exists as a symlink
to /var/cfengine/bin/cfbs making 'sudo cfbs' work in
environments where /usr/local/sbin is in sudo secure_path
> Create a symlink for cfbs in /usr/local/sbin

- packaging/common/cfengine-hub/postinstall.sh
Just like we do with many other executables we ship in /var/cfengine/bin.
Ticket: ENT-10936
Changelog: /usr/local/sbin/cfbs now exists as a symlink
to /var/cfengine/bin/cfbs making 'sudo cfbs' work in
environments where /usr/local/sbin is in sudo secure_path
(cherry picked from commit 5881f0f670bb96c8ec8c3f8da0cb678cf3565dad)
> [3.21.x] Create a symlink for cfbs in /usr/local/sbin

- packaging/common/cfengine-hub/preinstall.sh
We have observed the presence of an old backup directory causing issues during
upgrade. This change avoids proceeding with package installation if a backup
directory exists and is not empty.
Previously this was restricted to when we thought we would be doing a database
migration, but we have seen issues with failed migration when the backup
directory is non-empty and we are not doing any migration, so it is better to
simply avoid installing the package if the backup directory is not empty even if
we don't expect to use it for migration.
Ticket: ENT-11233
> ENT-11233: Aborted package installation if backup directory exists non-empty

- ci/cfengine-build-host-setup.cf
- ci/install-python2-pip.sh
- ci/linux-install-jdk21.sh
- ci/setup-cfengine-build-host.sh
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
This is done via an rpm macro.
Build host policy is updated to included needed packages to achieve this. Only on rhel-8.
rhel-9 apparently removed this platform-python as dnf requires python39.
Ticket: ENT-11338
(cherry picked from commit c307618b14e7b2d6b21e9bd863c9e1c4ab1e6387)
Conflicts:
ci/cfengine-build-host-setup.cf
I added all of the build host related files in this commit to 3.21.x as we can track different build host setups eventually to be used in our pipelines instead of relying on external host setup/spawning in jenkins clouds. (ENT-5964 TODO)
> ENT-11338: Adjusted cfbs packaging on rhel-8 to use platform-python (3.21)

- packaging/common/cfengine-hub/postinstall.sh
The postinstall scriptlet on hub copies masterfiles and web UI to separate the pristine original version from the working copy ready for customization. By using `--reflink=auto` will tell `cp` to try to use reflinks if possible which makes the copy much faster on file systems with reflinks enabled (XFS, btrfs, bcachefs,...). It also saves disk space, but checking `du -sh /var/cfengine` gives the same result because `du` doesn't inspect the FS into such detail.
Ticket: none
Changelog: Postinstallation scriptlets of hub packages now use
reflinks to copy masterfiles and web UI files if
possible
> Use reflinks if possible for copying masterfiles and web UI

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-community/debian/cfengine-community.install
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova-hub/debian/cfengine-nova-hub.install
- packaging/cfengine-nova-hub/debian/rules
- packaging/cfengine-nova/cfengine-nova.spec.in
- packaging/cfengine-nova/debian/cfengine-nova.install
- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
Runalerts is now part of cf-reactor with no stamp files.
Ticket: ENT-11538
https://github.com/cfengine/nova/pull/2208
https://github.com/cfengine/core/pull/5487
https://github.com/cfengine/masterfiles/pull/2878
https://github.com/cfengine/buildscripts/pull/1407
> Drop cf-runalerts.service and the runalerts stamp directory

- packaging/cfengine-nova/cfengine-nova.wxs
otherwise, cf-secret.exe was packaged into *.msi, but not installed on
a target machine
Ticket: ENT-10405
(cherry picked from commit 1042d0bfce99ba294ac2e3c01b396514184b606c)
> ENT-10405: Added cf-secret ComponentRef (3.18)

- deps-packaging/lmdb/distfiles
For some reason the checksum changed even though the source version/tag has not.
I checked manually and the checksum is indeed different.
Ticket: ENT-11798
> ENT-11798: Updated openldap-LMDB checksum

- build-scripts/detect-environment
Jenkins failed with "Unknown RHEL Server version: 8.10" because the
`detect-environment` script did not take into account that the minor
version number can have more than one decimal.
Ticket: ENT-11808
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10801)](https://ci.cfengine.com/job/pr-pipeline/10801/)
> ENT-11808: detect-environment: Fixed version detection for RHEL

- build-scripts/detect-environment
Jenkins failed with "Unknown RHEL Server version: 8.10" because the `detect-environment` script did not take into account that the minor version number can have more than one decimal.
Ticket: ENT-11808
(cherry picked from commit 4f0a6ba6b074a119032c31cae5478185ad947011)
Back ported from https://github.com/cfengine/buildscripts/pull/1423
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10809)](https://ci.cfengine.com/job/pr-pipeline/10809/)
> ENT-11808: detect-environment: Fixed version detection for RHEL (3.21.x)

- build-scripts/detect-environment
Jenkins failed with "Unknown RHEL Server version: 8.10" because the
`detect-environment` script did not take into account that the minor
version number can have more than one decimal.
Ticket: ENT-11808
(cherry picked from commit 4f0a6ba6b074a119032c31cae5478185ad947011)
Back ported from https://github.com/cfengine/buildscripts/pull/1423
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10810)](https://ci.cfengine.com/job/pr-pipeline/10810/)
> ENT-11808: detect-environment: Fixed version detection for RHEL (3.18.x)

- packaging/common/cfengine-hub/postinstall.sh
Why is it even there? My guess is that the call to
inventory_variables_refresh was there because of something that was
rendered obsolete after moving this maintenance to cf-reactor.
Ticket: ENT-11763
> ENT-11763: postinstall.sh: Removed call to inventory_variables_refresh

- packaging/common/cfengine-hub/preinstall.sh
This change simply aims to make the amount of free disk space desired more clear.
Ticket: ENT-11835
(cherry picked from commit ca203fe2dd81a0e982dc7c50bf80ca945e24ca3a)
> ENT-11835: Improved messages about free space desired for hub upgrade (3.21)

- packaging/common/cfengine-hub/preinstall.sh
This change simply aims to make the amount of free disk space desired more clear.
Ticket: ENT-11835
(cherry picked from commit ca203fe2dd81a0e982dc7c50bf80ca945e24ca3a)
> ENT-11835: Improved messages about free space desired for hub upgrade (3.18)

- build-scripts/build-environment-check
- build-scripts/labels.txt
- deps-packaging/rsync/cfbuild-rsync.spec
- deps-packaging/rsync/debian/rules
- deps-packaging/rsync/fix-buffer-overflow.patch
Ticket: ENT-11309
Back ported to:
- https://github.com/cfengine/buildscripts/pull/1420
- https://github.com/cfengine/buildscripts/pull/1421
> ENT-11309: Added Ubuntu 24 to labels.txt

- build-scripts/build-environment-check
- build-scripts/labels.txt
- deps-packaging/rsync/cfbuild-rsync.spec
- deps-packaging/rsync/debian/rules
- deps-packaging/rsync/fix-buffer-overflow.patch
Ticket: ENT-11309
(cherry picked from commit e48089a7dea2855cc6324fd6e27ff79365be6b7b)
Back ported from https://github.com/cfengine/buildscripts/pull/1419
> ENT-11309: Added Ubuntu 24 to labels.txt (3.21.x)

- build-scripts/build-environment-check
- build-scripts/labels.txt
- deps-packaging/rsync/cfbuild-rsync.spec
- deps-packaging/rsync/debian/rules
- deps-packaging/rsync/fix-buffer-overflow.patch
Ticket: ENT-11309
(cherry picked from commit e48089a7dea2855cc6324fd6e27ff79365be6b7b)
Back ported from https://github.com/cfengine/buildscripts/pull/1419
> ENT-11309: Added Ubuntu 24 to labels.txt (3.18.x)

- deps-packaging/apache/httpd.conf
Apache often logs errors related to IPv6, e.g.:
No route to host: AH00056: connect to listener on [::]:80
Specifying IPv4 when listening on port 80 prevents this excessive noise.
Ticket: ENT-10646
- https://github.com/cfengine/masterfiles/pull/2901
> ENT-10646: Squashed common error logged by Apache related to IPv6

- deps-packaging/apache/httpd.conf
Apache often logs errors related to IPv6, e.g.:
No route to host: AH00056: connect to listener on [::]:80
Specifying IPv4 when listening on port 80 prevents this excessive noise.
Ticket: ENT-10646
(cherry picked from commit a99ca365c5a45ac044b8c3629edcb54ae036c097)
> ENT-10646: Squashed common error logged by Apache related to IPv6 (3.21)

- deps-packaging/apache/httpd.conf
Apache often logs errors related to IPv6, e.g.:
No route to host: AH00056: connect to listener on [::]:80
Specifying IPv4 when listening on port 80 prevents this excessive noise.
Ticket: ENT-10646
(cherry picked from commit a99ca365c5a45ac044b8c3629edcb54ae036c097)
> ENT-10646: Squashed common error logged by Apache related to IPv6 (3.18)

- build-scripts/test-on-testmachine
Issue was that on Ubuntu 24, they are sometimes spawned by apt and left
running in chroot. This fix has previously been used on SUSE platforms
(see ticket ENT-6139).
Ticket: None
> Ignore gpg-agents lingering in chroot on Ubuntu 24

- build-scripts/test-on-testmachine
Issue was that on Ubuntu 24, they are sometimes spawned by apt and left
running in chroot. This fix has previously been used on SUSE platforms
(see ticket ENT-6139).
Ticket: None
(cherry picked from commit 53e8f602d6345d13cccd0527388806d1215e8e6a)
Back ported from https://github.com/cfengine/buildscripts/pull/1452/commits
> Ignore gpg-agents lingering in chroot on Ubuntu 24 (3.18.x)

- build-scripts/test-on-testmachine
Issue was that on Ubuntu 24, they are sometimes spawned by apt and left
running in chroot. This fix has previously been used on SUSE platforms
(see ticket ENT-6139).
Ticket: None
(cherry picked from commit 53e8f602d6345d13cccd0527388806d1215e8e6a)
Back ported from https://github.com/cfengine/buildscripts/pull/1452/commits
> Ignore gpg-agents lingering in chroot on Ubuntu 24 (3.21.x)

- packaging/common/cfengine-hub/postinstall.sh
The hostname(1) man page says for the '-i' option:
Avoid using this option; use hostname --all-ip-addresses instead.
where '-I' is the short version of '--all-ip-addresses' for which:
The loopback interface and IPv6 link-local addresses  are  omitted.
So we don't have to filter those out and worry about the link-local addresses reported like this:
fe80::cf:85ff:fe1c:54d7%enX0
which is not a valid IP address and OpenSSL fails on it.
Ticket: ENT-7598
> Only use 'hostname -I' to get local IPs for subjectAltName

- packaging/common/cfengine-hub/postinstall.sh
The hostname(1) man page says for the '-i' option:
Avoid using this option; use hostname --all-ip-addresses instead.
where '-I' is the short version of '--all-ip-addresses' for which:
The loopback interface and IPv6 link-local addresses  are  omitted.
So we don't have to filter those out and worry about the link-local addresses reported like this:
fe80::cf:85ff:fe1c:54d7%enX0
which is not a valid IP address and OpenSSL fails on it.
Ticket: ENT-7598
(cherry picked from commit 8356635a4af04024f70eeff11663c80f97bd047b)
> [3.18.x] Only use 'hostname -I' to get local IPs for subjectAltName

- packaging/common/cfengine-hub/postinstall.sh
The hostname(1) man page says for the '-i' option:
Avoid using this option; use hostname --all-ip-addresses instead.
where '-I' is the short version of '--all-ip-addresses' for which:
The loopback interface and IPv6 link-local addresses  are  omitted.
So we don't have to filter those out and worry about the link-local addresses reported like this:
fe80::cf:85ff:fe1c:54d7%enX0
which is not a valid IP address and OpenSSL fails on it.
Ticket: ENT-7598
(cherry picked from commit 8356635a4af04024f70eeff11663c80f97bd047b)
> [3.21.x] Only use 'hostname -I' to get local IPs for subjectAltName

- ci/setup-cfengine-build-host.sh
Oops, wrong pwd for `git log -1` command, need to use `-C buildscripts`
> Adjusted debug log message for build host setup script

- ci/cfengine-masterfiles-3.21.4-1.pkg.tar.gz.sha256
- ci/setup-cfengine-build-host.sh
3.21.5 introduced a behavior change for simple package promises without any attributes resulting in errors in the build host policy.
Ticket: ENT-11989
> ENT-11898: Revert to using 3.21.4 version for build host setup

- ci/setup-cfengine-build-host.sh
-C <dir> wasn't supported on CentOS-6
> ENT-11898: Adjusted build host setup script for older git versions

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
We started getting reports of issues related to an upstream bug in
chkconfig, (it failed to install if /etc/init.d had been created already). While
not our issue, it highlighted that it's probably time to remove the old init
script from modern packages.
Ticket: ENT-11901
> ENT-11901: Removed /etc/init.d/cfengine3 from EL9+ packages

- packaging/common/cfengine-hub/postinstall.sh
pg_upgrade calls postgres which includes reference to libssl that may change during upgrade which will cause postgres to not be executable
Add LD_LIBRARY_PATH=$BACKUP_DIR/lib/ to address this issue.
Ticket: ENT-11853
> ENT-11853: Adjusted calling pg_upgrade during upgrade to include LD_LIBRARY_PATH of previous installation

- ci/Dockerfile-cfengine-build-package
- ci/junit-text-summary.sh
- When the junit xml file is not found, exit 0 to show a nicer result in GH actions summary
- Added a quick-fail if archive.ubuntu.com is unavailable
> junit summary failure improvement/3.21

- ci/setup-cfengine-build-host.sh
- **Update quick-install script sha for build host setup script**
- **Use latest LTS (3.24.0) for all build host setups**
> latest lts for build hosts

- ci/cfengine-masterfiles-3.24.0-1.pkg.tar.gz.sha256
Needed after version used for build host setup to 3.24.0
Ticket: none
> Added sha for 3.24.0 masterfiles tarball

- README.md
Added note to refer to master README.md and individual files instead of README.md in LTS branches.
Ticket: ENT-12140
> Removed dependency tables in 3.21.x LTS branch

- deps-packaging/apache/httpd.conf
> ENT-4400: Added Content-Security-Policy header to the Apache httpd config

- deps-packaging/apache/httpd.conf
Ticket: ENT-4400
(cherry picked from commit eb2ffa3d6d476929fb02fa969ca3359131aa5bf9)
> ENT-4400: Added Content-Security-Policy header to the Apache httpd config (3.21.x)

- deps-packaging/apache/httpd.conf
Ticket: ENT-4400
(cherry picked from commit eb2ffa3d6d476929fb02fa969ca3359131aa5bf9)
> ENT-4400: Added Content-Security-Policy header to the Apache httpd config (3.24.x)

- packaging/common/cfengine-hub/postinstall.sh
If pg_upgrade fails it is OK because we have several other options which we try during hub package upgrade.
It is likely that pg_upgrade will fail when upgrading major versions of postgresql during the hub package upgrade.
Sadly, since we build postgresql to link to /var/cfengine/lib (WORKDIR/lib) the pg_upgrade utility can fail due to old-bin binaries trying to use the newer libraries and missing symbols.
If we followed the pattern of placing each set of postgresql binaries, libraries, etc in a major-versioned directory this would not be an issue.
However, making that change seems too large and doesn't handle previous versions of CFEngine hub package well.
To see the errors, run the upgrade with DEBUG=1 defined as an environment variable.
Ticket: ENT-12383
> Adjusted hub upgrade database migration to show only actionable logs

- packaging/common/cfengine-hub/postinstall.sh
- Adjusted hub upgrade database migration to show only actionable logs
- Revert "Adjusted calling pg_upgrade during upgrade to include LD_LIBRARY_PATH of previous installation"
> Adjusted hub upgrade database migration to show only actionable logs (3.24)

- build-scripts/build-environment-check
- ci/cfengine-build-host-setup.cf
Want to check this as early as possible to save on resource usage and people waiting time.
together:
https://github.com/cfengine/buildscripts/pull/1523
https://github.com/cfengine/nova/pull/2362
> Added check for psycopg2 python module for nova/tests/reporting

- ci/cfengine-build-host-setup.cf
Nova reporting tests have switched to preferring python3 if available, which it is on ubuntu >= 20.
> Install python3-psycopg2 on ubuntu >= 20

- ci/cfengine-build-host-setup.cf
Generally python3-psycopg2 is available so no need to install python2 based python-psycopg2 package.
> Adjusted installation of psycopg2 for build hosts

- build-scripts/build-environment-check
- ci/cfengine-build-host-setup.cf
- Fixed up version of psycopg2 module to install on redhat/centos 6 and 7 platforms
- Added check for psycopg2 python module for nova/tests/reporting
- Install python3-psycopg2 on ubuntu >= 20
> ENT-12432: Fixup python/pscopg2 for reporting tests (3.21)

- build-scripts/build-environment-check
- ci/cfengine-build-host-setup.cf
- Fixed up version of psycopg2 module to install on redhat/centos 6 and 7 platforms
- Added check for psycopg2 python module for nova/tests/reporting
- Install python3-psycopg2 on ubuntu >= 20
> ENT-12432: Fixup python/pscopg2 for reporting tests (3.24)

- ci/cfengine-build-host-setup.cf
Was breaking check_outputs tests related to peers because hostname -f and sys.fqhost were not matching.
Ticket: ENT-12437
> Adjusted build host policy for ubuntu-18 regarding hostname

- build-scripts/build-environment-check
This reverts commit 82dd64c0ddf338d137cb9925eaa3d68bcd1c5061.
The check for psycopg2 was too early and is present in nova/tests/reporting 'make check' and early enough.
> Revert "Added check for psycopg2 python module for nova/tests/reporting"

- build-scripts/build-environment-check
This reverts commit 82dd64c0ddf338d137cb9925eaa3d68bcd1c5061.
The check for psycopg2 was too early and is present in nova/tests/reporting 'make check' and early enough.
(cherry picked from commit a483cf681b5d8e2d76a089e9362b3f654b07010e)
> Revert "Added check for psycopg2 python module for nova/tests/reporting" (3.21)

- build-scripts/build-environment-check
- ci/cfengine-build-host-setup.cf
- ci/setup-cfengine-build-host.sh
- Various fixes for redhat/centos 7, 8, and 9
- fixed up promises.log of setting up build host to append instead of clobber
> Fixed up build host policy and build-environment-check for centos/redhat

- build-scripts/build-environment-check
- ci/cfengine-build-host-setup.cf
> Fixed build host policy and build-environment-check for centos-6

- build-scripts/build-environment-check
- ci/cfengine-build-host-setup.cf
- ci/setup-cfengine-build-host.sh
- Adjusted build host policy script to append all three runs to one promises.log
- Adjusted build host policy a bit for centos_9
- Adjusted build-environment-check to align with centos-7, redhat-8 and redhat-9
- Adjusted build host policy to disable debug packages only after rpm-build-libs is installed (redhat)
> Fixed up build host policy and build-environment-check for centos/redhat (3.21)

- build-scripts/build-environment-check
- ci/cfengine-build-host-setup.cf
- ci/setup-cfengine-build-host.sh
- Adjusted build host policy script to append all three runs to one promises.log
- Adjusted build host policy a bit for centos_9
- Adjusted build-environment-check to align with centos-7, redhat-8 and redhat-9
- Adjusted build host policy to disable debug packages only after rpm-build-libs is installed (redhat)
> Fixed up build host policy and build-environment-check for centos/redhat (3.24)

- packaging/common/cfengine-hub/postinstall.sh
- Adjusted hub upgrade database migration to show only actionable logs
- Revert "Adjusted calling pg_upgrade during upgrade to include LD_LIBRARY_PATH of previous installation"
```
Packaging changes:
- Adjusted calling pg_upgrade during upgrade to include LD_LIBRARY_PATH of previous installation
(ENT-11853)
```
> Adjusted hub upgrade database migration to show only actionable logs (3.21)

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
- packaging/common/cfengine-hub/preremove.sh
- packaging/common/cfengine-non-hub/preremove.sh
- Removed /etc/init.d/cfengine3 from EL9+ packages
- Only run 'chkconfig --del' on uninstall if we shipped /etc/init.d/cfengine3
- Fix RHEL version check in cfengine-community.spec.in
- Fix profile.d script name in cfengine-community.spec.in
> ENT-11901: Remove /etc/init.d/cfengine3 from EL8+ packages (3.21)

- ci/cfengine-build-host-setup.cf
And alphabetized the packages in that group.
It was a small portion so didn't want two commits: one for alpha, one for fix.
Ticket: ENT-12451
(cherry picked from commit ad0ede982f7cb457090634f61c9844674652355d)
> Restored rpm-build package installation for suse build hosts (3.21)

- build-scripts/install-dependencies
Missed using $PERL for the List::Utils exporting pairs check from 3.24.x deps upgrade.
https://github.com/cfengine/buildscripts/pull/1498/commits/fd6d251b5d22a7dced1175cfec5cbd870a0c3e40
Ticket: ENT-12366
> Fixed perl version check for openssl building (master)

- .github/workflows/build-using-buildscripts.yml
- .github/workflows/deployment-tests.yml
- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
We create a self-signed certificate and the CN must be 64 characters or less so use hostname -s instead of hostname -f and fail if even the short name is longer than 64 characters.
Ticket: CFE-4469
> Modified hub package install scriptlet to use hostname -s and fail if that is longer than 64 characters

- .github/workflows/build-using-buildscripts.yml
- .github/workflows/deployment-tests.yml
- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
- Modified hub package install scriptlet to use hostname -s and fail if that is longer than 64 characters
- Update actions/upload-artifact from v3 to v4 and remove packages from deployment-tests workflow artifacts
> Modified hub package install scriptlet to use hostname -s and fail if that is longer than 64 characters (3.21)

- .github/workflows/build-using-buildscripts.yml
- .github/workflows/deployment-tests.yml
- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-hub/preinstall.sh
- Modified hub package install scriptlet to use hostname -s and fail if that is longer than 64 characters
- Update actions/upload-artifact from v3 to v4 and remove packages from deployment-tests workflow artifacts
> Modified hub package install scriptlet to use hostname -s and fail if that is longer than 64 characters (3.24)

- .github/workflows/build-using-buildscripts.yml
- .github/workflows/deployment-tests.yml
- ci/Dockerfile-cfengine-build-package
- ci/Dockerfile-cfengine-deployment-tests
- ci/README
- ci/docker-build-package.sh
- ci/setup.sh
We were getting odd errors with ldap.so for php:
/usr/lib/php/20190902/ldap.so: undefined symbol: RETURN_THROWS
Ticket: ENT-12530
> Bumped CI ubuntu from 20 to 22

- ci/cfengine-build-host-setup.cf
> Added systemd-coredump for debian-based buildhosts for debugging failures

- deps-packaging/apache/httpd.conf
README files in build module repos often contain images, sometimes those images
are served from raw.github.com. This change allows those images to be displayed
within the Build app in Mission Portal.
Ticket: ENT-12531
Merge together: https://github.com/cfengine/masterfiles/pull/2973
> ENT-12531: Allowed images from raw.github.com

- deps-packaging/apache/httpd.conf
README files in build module repos often contain images, sometimes those images
are served from raw.github.com. This change allows those images to be displayed
within the Build app in Mission Portal.
Ticket: ENT-12531
(cherry picked from commit 694246214a4bf8dbd41546e53b683b1c4a6d4d03)
Merge together: https://github.com/cfengine/masterfiles/pull/2974
> ENT-12531: Allowed images from raw.github.com (3.24)

- deps-packaging/apache/httpd.conf
README files in build module repos often contain images, sometimes those images
are served from raw.github.com. This change allows those images to be displayed
within the Build app in Mission Portal.
Ticket: ENT-12531
(cherry picked from commit 694246214a4bf8dbd41546e53b683b1c4a6d4d03)
Merge together: https://github.com/cfengine/masterfiles/pull/2975
> ENT-12531: Allowed images from raw.github.com (3.21)

- build-scripts/bootstrap-tarballs
- ci/cfengine-build-host-setup.cf
* [Added php-curl dependency to bootstrap-pr host](https://github.com/cfengine/buildscripts/pull/1565/commits/96a5930290de8a46468f19eaefd3529db99400ba)
* [Remove const visibility modifiers in tcpdf_static.php](https://github.com/cfengine/buildscripts/pull/1565/commits/6cb6ae8f0a9f0a704ddc0f6c5f7abf5c70b3ad67)
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11577)](https://ci.cfengine.com/job/pr-pipeline/11577/)
> ENT-12565: Fixed bootstrap host after tcpdf 6.8.0 dependency upgrade

- build-remote
- build-scripts/test-on-testmachine
- build-scripts/transfer-results
- build-scripts/transfer-to-testmachine
An instance occurred where maybe the PWD was removed by another process and so an rsync command failed due to not being able to write the file in PWD.
Ticket: ENT-12633
> Change unused rsync.log path to specific /tmp/rsync.log

- build-remote
- build-scripts/test-on-testmachine
- build-scripts/transfer-results
- build-scripts/transfer-to-testmachine
An instance occurred where maybe the PWD was removed by another process and so an rsync command failed due to not being able to write the file in PWD.
Ticket: ENT-12633
(cherry picked from commit 3e5e3885b63656244606118ca919b5af9218f02d)
> Change unused rsync.log path to specific /tmp/rsync.log (3.21)

- build-remote
- build-scripts/test-on-testmachine
- build-scripts/transfer-results
- build-scripts/transfer-to-testmachine
An instance occurred where maybe the PWD was removed by another process and so an rsync command failed due to not being able to write the file in PWD.
Ticket: ENT-12633
(cherry picked from commit 3e5e3885b63656244606118ca919b5af9218f02d)
> Change unused rsync.log path to specific /tmp/rsync.log (3.24)

- ci/cfengine-build-host-setup.cf
apt-transport-https package is not easily installed so use http instead
Fix for jenkins-vms bootstrap vm.
Ticket: ENT-12659
> Adjusted cfengine build host policy to use http for debian-9

- ci/cfengine-build-host-setup.cf
Should work in most places. Mostly focused here on ENT-12669 bootstrap-pr segfaults during npm i in mission-portal.
Ticket: ENT-12669
> Added policy to enable core dumps on all build hosts

- ci/cfengine-build-host-setup.cf
In the event that we migrate to a different platform/version than ubuntu_16.
Ticket: none
> Adjusted mingw build host to only guard on mingw_build_host class

- ci/cfengine-build-host-setup.cf
`autoconf-archive` is required in order to resolve the macro `AX_PTHREAD`. Previously we used `ACX_PTHREAD`, but this macro is obsolete.
> Added autoconf-archive dependency to bootstrap-pr host

- build-scripts/bootstrap-tarballs
- ci/setup-projects.sh
Ticket: ENT-12660
(cherry picked from commit b743c80a93df2fe1eb14af47a032ec005293ab7c)
> ENT-12660: exclude npm dev dependencies from a package (3.24.x)

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
Otherwise, errors occur when removing the cfengine-nova package on suse-15+ systems.
Ticket: CFE-4077
> Added suse 15+ to agent packages which have init scripts removed

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-community/debian/cfengine-community.install
- packaging/cfengine-nova/cfengine-nova.spec.in
- packaging/cfengine-nova/debian/cfengine-nova.install
These were added with CFE-2278, commit fdbe42f4b54e02230602a4d76b0a50aad4efe23c when split systemd units were introduced.
Ticket: ENT-12689
> Remove enterprise hub systemd units from community and enterprise agent packages

- packaging/cfengine-nova/cfengine-nova.wxs
> Fixed inclusion of libleech_0.dll in Windows package

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
Otherwise, errors occur when removing the cfengine-nova package on suse-15+ systems.
Ticket: CFE-4077
(cherry picked from commit 327055bde4e1b81f69d4ed3219bd486dc899344e)
> Added suse 15+ to agent packages which have init scripts removed (3.24)

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
Otherwise, errors occur when removing the cfengine-nova package on suse-15+ systems.
Ticket: CFE-4077
(cherry picked from commit 327055bde4e1b81f69d4ed3219bd486dc899344e)
> Added suse 15+ to agent packages which have init scripts removed (3.21)

- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-community/debian/cfengine-community.install
- packaging/cfengine-nova/cfengine-nova.spec.in
- packaging/cfengine-nova/debian/cfengine-nova.install
These were added with CFE-2278, commit fdbe42f4b54e02230602a4d76b0a50aad4efe23c when split systemd units were introduced.
Also explicitly remove the new cf-php-fpm service needed for http2 enablement in Mission Portal (ENT-11440).
Ticket: ENT-12689
(cherry picked from commit 006d3dff46d5124262655490f803ecc1b1caa1ce)
Conflicts:
packaging/cfengine-community/cfengine-community.spec.in
packaging/cfengine-community/debian/cfengine-community.install
packaging/cfengine-nova/cfengine-nova.spec.in
packaging/cfengine-nova/debian/cfengine-nova.install
3.21 does not include cf-php-fpm
> Remove enterprise hub systemd units from community and enterprise agent packages. (3.21)

- deps-packaging/diffutils/cfbuild-diffutils-aix.spec
- deps-packaging/diffutils/cfbuild-diffutils.spec
- deps-packaging/leech/cfbuild-leech.spec
- deps-packaging/libexpat/cfbuild-libexpat.spec
- deps-packaging/libgcc/cfbuild-libgcc.spec
- deps-packaging/libiconv/cfbuild-libiconv.spec
- deps-packaging/librsync/cfbuild-librsync.spec
- deps-packaging/lmdb/cfbuild-lmdb.spec
- packaging/cfengine-community/cfengine-community.spec.in
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.aix.in
- packaging/cfengine-nova/cfengine-nova.spec.in
Discussed in Slack.
We build our own cfbuild- prefixed packages, nobody else should
really be installing these, but	if there is a problem with them
it's really more appropriate to	point to cfengine.com.
(To contact / blame us).
> Further standardized Url fields in spec files

- .github/workflows/update-deps.py
- .github/workflows/update-deps.yml
TODO:
Back ported to https://github.com/cfengine/buildscripts/pull/1597
> ENT-12597: Added automatic dependency updates

- .github/workflows/update-dep-tables.yml
- README.md
- scripts/README.md
- scripts/deptool.py
- **deptool / GH Action: Small grammar fix - dependencies tables vs dependency tables**
- **README.md: Reformatted with prettier**
- **scripts/README.md: Reformatted with prettier**
- **deptool: Changed default path to cwd (.)**
- **scripts/README.md: Switched to one sentence per line style**
- **README.md: Reformatted to use one sentence per line style**
- **deptool / READMEs: Removed colons from headings**
> Smaller fixes to deptool, related GH Action, and READMEs

- README.md
Discussed with Lars and Jakub, probably makes more sense to not list
in dependency tables.
> README.md: Removed libgcc from dependency tables

- README.md
- scripts/README.md
- scripts/deptool.py
- **READMEs: Updated to always use left justified text table cells**
- **deptool: Updated to work with colons for left justified table cells**
- **scripts/README.md: Updated all examples to assume repo root**
> deptool / READMEs: Left justified columns in Markdown dependency tables

- deps-packaging/openssl/0001-Revert-rcu-Ensure-that-updates-to-the-ID-field-of-a-.patch
- deps-packaging/openssl/0002-Don-t-use-__ATOMIC_ACQ_REL-on-older-compilers.patch
- deps-packaging/openssl/cfbuild-openssl.spec
- deps-packaging/openssl/distfiles
- deps-packaging/openssl/hpux/build
- deps-packaging/openssl/source
- **Updated dependency 'openssl' from version 3.4.0 to 3.4.1**
- **Fixed openssl on HP-UX**
Back-ported to https://github.com/cfengine/buildscripts/pull/1648
> CFE-4510: Updated dependency 'openssl' from version 3.4.0 to 3.4.1

- deps-packaging/php/cfbuild-php.spec
- deps-packaging/php/debian/cfbuild-php.install
- deps-packaging/php/debian/rules
- packaging/common/cfengine-hub/postinstall.sh
> Removed php module for apache, replaced with php-fpm

- packaging/common/cfengine-hub/postinstall.sh
Ticket: ENT-12185
together: 
- https://github.com/cfengine/mission-portal/pull/2782
- https://github.com/cfengine/nova/pull/2402
- https://github.com/cfengine/buildscripts/pull/1628
- https://github.com/cfengine/system-testing/pull/603
> ENT-12185: Moved CFE_ROBOT user creation from MP cli task to shell script & Print setup code in the postinstall scripts

- .github/workflows/update-deps.yml
GitHub docs say that scheduled workflows will only run on the default branch.
This commit:
- Adds branch matrix to run updates on both master and 3.24.x branches
- Configures branch-specific settings (major bumps for master, minor for 3.24.x)
Ticket: ENT-12711
> Added 3.24.x branch to scheduled dependency updates workflow

- ci/docker-build-package.sh
Was getting an "operation not permitted" for a chmod command on the core sub-directory for nova builds.
Ticket: ENT-10487
> Fixed copying artifacts directory from container

- README.md
Reverts cfengine/buildscripts#1684
So we can test the GH Action a bit more.
> Revert "Updated Markdown dependency tables"

- deps-packaging/openssl/cfbuild-openssl.spec
In cd0bc8206a0b4a60ad72b416825c316a2dcb794a I both removed the 0001 and 0002 patches for centos/rhel-6 but also incorrectly removed patches 0006 and 0008.
Restoring them here.
Ticket: ENT-12761
aix only build: [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12042)](https://ci.cfengine.com/job/pr-pipeline/12042/)
> Reverting incorrect removal of patches for openssl dependency (3.24)

- build-scripts/bootstrap-tarballs
- build-scripts/package
tcpdf >= 6.8.0 requires php 7.1+ but we bootstrap for 3.21.x on debian-9 and sury.org has no stretch packages of newer php versions.
Use built php instead.
Ticket: ENT-12777
ubu16hub only build: [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12054)](https://ci.cfengine.com/job/pr-pipeline/12054/)
> Moved tcpdf_add_font calls from bootstrap, to package step (3.21)

- build-scripts/bootstrap-tarballs
- build-scripts/package
tcpdf >= 6.8.0 requires php 7.1+ but we bootstrap for 3.21.x on debian-9 and sury.org has no stretch packages of newer php versions.
Use built php instead.
Ticket: ENT-12777
(cherry picked from commit 177d48a645ddf6b1cd6cd3918bc3e877a443e540)
> Moved tcpdf_add_font calls from bootstrap, to package step (3.24)

- build-scripts/exotics.txt
Removed suse-11, aix-5.3, solaris-10 (sparc and x86).
All of these were not being built because they are not in labels.txt but might as well remove them to keep things tidy.
Ticket: none
> Tidy up exotics platforms (3.21.x)

- deps-packaging/php/debian/rules
Ubuntu 16 has an old compiler which improperly indicates support for avx512 (Advanced Vector Extensions) and so later fails during the build.
For this platform we force disabling this feature with -mno-avx512f.
Ticket: ENT-12945
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12058)](https://ci.cfengine.com/job/pr-pipeline/12058/)
> Disabled avx512 feature when compiling php on Ubuntu 16 (3.21)

- deps-packaging/php/debian/rules
Accidentally made the php build ONLY work on ubuntu 16 by not providing an "else" case in debian/rules
Ticket: ENT-12945
> Fixed avx512 ubuntu 16 php compile fix (3.21)

- build-scripts/bootstrap-tarballs
- build-scripts/package
- ci/cfengine-build-host-setup.cf
- Revert "Added php-curl dependency to bootstrap-pr host"
- Revert "Remove const visibility modifiers in tcpdf_static.php"
- Moved tcpdf_add_font calls from bootstrap, to package step
bootstrap-pr job is green! [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=bootstrap-pr&build=955)](https://ci.cfengine.com/job/bootstrap-pr/955/) (I cancelled the rest of the job after, good enough for me)
> Moved tcpdf_add_font calls from bootstrap, to package step (master)

- build-scripts/package
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
We build against systems with the latest available dependencies such as OpenSSL.
libcurl builds against this OpenSSL version which can have API changes that will break functionality if used on a non-updated system.
Ticket: ENT-12587
> Fixed issue where rhel >8 packages would not have correct openssl dependency version

- build-scripts/package
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
libcurl will likely have a hard dependency on the exact version so include it in our Requires: entries.
Ticket: ENT-12587
(cherry picked from commit 6fc4077622953ee602d6d6cfcdeb2bf4601891e2)
> Fixed issue where rhel >8 packages would not have correct openssl dependency version (3.21)

- build-scripts/package
- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova/cfengine-nova.spec.in
libcurl will likely have a hard dependency on the exact version so include it in our Requires: entries.
Ticket: ENT-12587
(cherry picked from commit 6fc4077622953ee602d6d6cfcdeb2bf4601891e2)
> Fixed issue where rhel >8 packages would not have correct openssl dependency version (3.24)

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/common/cfengine-hub/postinstall.sh
- packaging/common/cfengine-non-hub/postinstall.sh
- Added hostname package dependency for rpm hub package
- Added better check for systemd presence
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12143)](https://ci.cfengine.com/job/pr-pipeline/12143/)
> Adjustments for running hub in non-priv/non-systemd container

- .github/workflows/ci.yml
The workflow event must be pull_request in order for the scripts to know what baseref (branch) to use for dependent repos.
Before this change master branch worked fine but branch dependency PRs from github-actions(bot) would fail due to always checking out master.
Ticket: ENT-13038
(cherry picked from commit 0621c0637394cdef37993a05a50eb27986c0ade9)
Conflicts:
.github/workflows/build-using-buildscripts.yml
We don't want to bring build-using-buildscripts.yml changes from 3.24.x, only the fix for when to run.
> Restrict workflow runs to cfengine organization pull requests

- ci/cfengine-build-host-setup.cf
- ci/linux-install-jdk21.sh
On older hosts we were getting away with jdk 11 but that isn't sufficient for impending jenkins upgrade.
This needs to hold-off while jenkins-dev is still in testing.
Ticket: ENT-13033
> Force all jenkins build hosts to use jdk 21

- ci/linux-install-jdk21.sh
Previously updated checksum due to new version of JDK, but forgot to
update version number.
> linux-install-jdk21.h: also update version number

- ci/linux-install-jdk21.sh
This is needed because /latest is unstable and we want to ensure stability and check checksums that we collect manually or eventually through pull request automation for human confirmation.
Ticket: ENT-13114
> Adjusted linux-install-jdk21.sh to be stable at latest-1 version

- deps-packaging/libcurl-hub/debian/rules
- deps-packaging/libcurl/debian/rules
- deps-packaging/libcurl/hpux/build
- deps-packaging/libcurl/solaris/build
```
configure: WARNING: unrecognized options: --with-pthread, --without-axtls, --without-cyassl, --without-egd-socket, --without-libidn, --without-nss, --without-polarssl, --without-winssl
```
> Removed unrecognized options when configuring libcurl

- build-scripts/compile
- **compile: fixed shellcheck issues**
- **compile: Reduced verbosity of script**
- **compile: Fixed inconsistent indents**
- **compile: Placed block terminator on a new line for consistency**
- **compile: Documented script**
Build with no tests
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12277)](https://ci.cfengine.com/job/pr-pipeline/12277/)
Example output:
```
$ PROJECT=nova ROLE=hub ./buildscripts/build-scripts/compile
---snip---
compile: Debug: Running make in core repo...
compile: Debug: Running make install in core repo...
compile: Debug: Running make in enterprise repo...
compile: Debug: Running make install in enterprise repo...
compile: Debug: Running make in nova repo...
compile: Debug: Running make install in nova repo...
compile: Debug: …
```
> ENT-12600: compile: Documented/refactored script

- build-scripts/create-empty-test
> ENT-12600: create-empty-test: Fixed shellcheck issues and simplified

- build-scripts/generate-source-tarballs
- **generate-source-tarballs: Documented script**
- **generate-source-tarballs: fixed shellcheck issues**
Example output:
```
generate-source-tarballs: debug: Running target make dist in core repository...
generate-source-tarballs: debug: Running target make dist in masterfiles repository...
```
Build with no tests:
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12420)](https://ci.cfengine.com/job/pr-pipeline/12420/)
> ENT-12600: generate-source-tarballs: Documented and refactored script

- build-scripts/configure
- build-scripts/detect-environment
- build-scripts/install-dependencies
- build-scripts/package
- deps-packaging/pkg-build-rpm
Build with exotics and no tests
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12261)](https://ci.cfengine.com/job/pr-pipeline/12261/)
^ Build failures are unrelated:
- SUSE 15 [ENT-13067](https://northerntech.atlassian.net/browse/ENT-13067)
- Solaris 11 [INF-3538](https://northerntech.atlassian.net/issues/INF-3538)
[ENT-13067]: https://northerntech.atlassian.net/browse/ENT-13067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INF-3538]: https://northerntech.atlassian.net/browse/INF-3538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENT-12600: detect-environment: Document and refactor

- build-scripts/functions
Ticket: ENT-13158
Build on AIX & Ubuntu with no tests
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12464)](https://ci.cfengine.com/job/pr-pipeline/12464/)
> run_and_print_on_failure(): fixed mktemp not found on AIX

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova-hub/debian/rules
The MPF enforces permissions of 400 and group and user ownership of root. While
the mis-alignment stabilizes, it does cause verification errors for RPM packages
that persists. This change brings the packaged permissions of share/GUI in
alignment with the MPF.
Ticket: ENT-13161
> ENT-13161: Aligned Hub package perms for share/GUI on EL and Debian platforms with the MPF

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova-hub/debian/conffiles
related to management of share/GUI and not-share/GUI of two php configuration files: https://github.com/cfengine/masterfiles/pull/2988
Ticket: ENT-12658
> Marked application/config/config.php as a configuration file in packages

- build-scripts/compile-options
- ci/cfengine-build-host-setup.cf
- **some random suse related requirements for non-aws instances**
- **Adjusted compile-options to not bundle OpenSSL on newer SuSE systems due to libpam/openssl incompatability**
> Adjusted compile-options to not bundle OpenSSL on newer SuSE systems due to libpam/openssl incompatability

- build-scripts/compile-options
- ci/cfengine-build-host-setup.cf
- **Changed suse-15 to use system openssl as redhats do**
- **Adjusted compile-options to not bundle OpenSSL on newer SuSE systems due to libpam/openssl incompatability**
> Adjusted compile-options to not bundle OpenSSL on newer SuSE systems due to libpam/openssl incompatability (3.21)

- packaging/cfengine-nova-hub/cfengine-nova-hub.spec.in
- packaging/cfengine-nova-hub/debian/conffiles
- packaging/cfengine-nova-hub/debian/rules
- **Aligned Hub package perms for share/GUI on EL and Debian platforms with the MPF**
- **Marked config.php files in share/GUI folder as configuration files in packages**
> Two fixes about share/gui in packaging ENT-12658, ENT-13161 (3.24)

- packaging/common/cfengine-hub/preinstall.sh
Added --no-run-if-empty option to some find | xargs commands.
Ticket: ENT-13214
(cherry picked from commit 224d4b705977ccd4c5745ce67ac8d5477ddfe185)
> Adjust hub packaging scripts in cases where no files are found during upgrade (3.21)

- packaging/common/cfengine-hub/preinstall.sh
Added --no-run-if-empty option to some find | xargs commands.
Ticket: ENT-13214
(cherry picked from commit 224d4b705977ccd4c5745ce67ac8d5477ddfe185)
> Adjust hub packaging scripts in cases where no files are found during upgrade (3.24)

- build-scripts/functions
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12588)](https://ci.cfengine.com/job/pr-pipeline/12588/)
> Grep for warnings in run_and_print_on_failure function

- build-scripts/functions
Fixed use of illegal option -C while grepping for error and warning
messages in `run_and_print_on_failure` on HP-UX.
```
grep: illegal option -- C
```
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12705)](https://ci.cfengine.com/job/pr-pipeline/12705/)
> functions: removed use of illegal grep option on HP-UX

- ci/linux-install-jdk21.sh
This reverts commit 5d24969295d5c9c3b4976b3d0e05968d28ac7dd9.
We need latest minor -1, so 21.0.8 is latest but not in /archive/ so we need to stick with 21.0.7 for now.
> Revert "Updated Java Development Kit to 21.0.8"

- deps-packaging/apache/httpd.conf
HTTP_HOST can be manipulated via Host header and for this reason http to https redirect will be handled on the UI.
Ticket: ENT-11481
together: https://github.com/cfengine/mission-portal/pull/2906
>  ENT-11481: Removed web server redirect from http to https 

- build-scripts/prepare-testmachine
- **prepare-testmachine: documented script**
- **prepare-testmachine: decreased verbosity of script**
- **prepare-testmachine: added logging to aid debugging**
> ENT-12600: prepare-testmachine: documented & refactored script

- deps-packaging/apache/httpd.conf
HTTP_HOST can be manipulated via Host header and for this reason http to https redirect will be handled on the UI.
Ticket: ENT-11481
(cherry picked from commit ac7b17c51e713063b7d3bec1d5a368ffa84b0bae)
> ENT-11481: Removed web server redirect from http to https (3.24.x)
